{
  actor
  {
    entitySearch(query: "{{nrql_query}}") 
    {
      count
      query
      results
      {
        entities
        {
          reporting
          guid
          name
        }
      }
    }
  }
}
