name: kubernetes-integration
displayName: Kubernetes Integration
description: New Relic install recipe for Kubernetes
repository: https://github.com/newrelic/nri-kubernetes

installTargets:
  - type: host
    os: linux

keywords:
  - Kubernetes
  - Pixie

successLinkConfig:
  type: EXPLORER

preInstall:
  info: |2
      Kubernetes:

install:
  version: "3"
  silent: true

  tasks:
    default:
      cmds:
        - task: start

    start:
      cmds:
        - |
          kubectl get pods --all-namespaces

postInstall:
  info: |2
      ⚙️  Kubernetes completed
