name: oracle-open-source-integration
displayName: Oracle Database Open Source Integration
description: New Relic install recipe for default Oracle Database Open Source on-host integration (via Infra-Agent)
repository: https://github.com/newrelic/nri-oracledb

dependencies:
  - infrastructure-agent-installer

installTargets:
  - type: host
    os: linux
    kernelArch: x86_64

# keyword convention for dealing with search terms that could land someone on this instrumentation project
keywords:
  - Infrastructure
  - Integration
  - oracle

# CLI runs process detection; this is used to filter recipes that are appropriate for matched processes
processMatch:
  - oracle

preInstall:
  requireAtDiscovery: |
    exit 132
  info: |2
      To capture data from the Oracle database integration, you'll first need to meet these prerequisites:
      - Oracle database version requirement (see https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/oracle-database-monitoring-integration/#comp-req)

install:
  version: "3"
  silent: true

  tasks:
    default:
      cmds:
        - task: setup

    setup:
      cmds:
        - |
          exit 131

postInstall:
  info: |2
      ⚙️  The Oracle database configuration file can be found in /etc/newrelic-infra/integrations.d/oracledb-config.yml
      Edit this file to make changes or configure advanced features for this integration. See the docs for options:
      https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/oracle-database-monitoring-integration#configuration
