name: apache-open-source-integration
displayName: Apache Open Source Integration
description: New Relic install recipe for default Apache Open Source on-host integration (via Infra-Agent)
repository: https://github.com/newrelic/nri-apache

installTargets:
  - type: host
    os: linux
    platform: "debian"
  - type: host
    os: linux
    platform: "ubuntu"

# keyword convention for dealing with search terms that could land someone on this instrumentation project
keywords:
  - Infrastructure
  - Integration
  - apache

# Examine Infrastructure events for correlated data
processMatch:
  - apache2

# Matches partial list of the Log forwarding parameters
# https://docs.newrelic.com/docs/logs/enable-log-management-new-relic/enable-log-monitoring-new-relic/forward-your-logs-using-infrastructure-agent#parameters
logMatch:
  - name: apache
    file: /var/log/apache2/*access.log
  - name: apache error
    file: /var/log/apache2/error.log

# NRQL the newrelic-cli will use to validate the agent/integration this recipe
# installed is successfully sending data to New Relic
validationNrql: "SELECT count(*) from ApacheSample where hostname like '{{.HOSTNAME}}' FACET entityGuid SINCE 10 minutes ago"

install:

  version: "3"
  silent: true

  tasks:
    default:
      cmds:
        - task: user_inputs
        - task: restart
        
    assert_pre_req:
      cmds:
        - |
          SERVICE_EXIST=$(sudo systemctl status newrelic-infra.service | grep "Active" | wc -l)
          if [ $SERVICE_EXIST -eq 0 ]; then
            echo "The newrelic-infra agent service is NOT installed on the host, but is required to install this integration." >> /dev/stderr
            exit 1
          fi

    user_inputs:
      cmds:
        - |
          if [ -z $NR_CLI_STATUS_URL ]; then
              echo "Apache status URL (default: http://127.0.0.1/server-status?auto):"
              read NR_CLI_STATUS_URL
              echo ""
              echo "Pure: $NR_CLI_STATUS_URL"
              echo "Try4: $TEST_NAME"
          fi
        - |
          echo "Try1: {{.NR_CLI_STATUS_URL}}"
          echo "Try2: ${NR_CLI_STATUS_URL}"
          echo "Try3: {{.NR_CLI_STATUS_URL}}"
          echo "Try4: $TEST_NAME"
          sudo mkdir -p "/etc/newrelic-infra/integrations.d"
        - |
          sudo apt-get update
        - |
          sudo apt-get install nri-apache -y
        - |
          if [ -f /etc/newrelic-infra/integrations.d/apache-config.yml ]; then
            sudo rm /etc/newrelic-infra/integrations.d/apache-config.yml;
          fi

          sudo cp /etc/newrelic-infra/integrations.d/apache-config.yml.sample /etc/newrelic-infra/integrations.d/apache-config.yml;

        - | 
          sudo tee /etc/newrelic-infra/integrations.d/apache-config.yml > /dev/null <<"EOT"
          integration_name: com.newrelic.apache

          instances:
              - name: apache-server-metrics
                command: metrics
                arguments:
                    status_url: $NR_CLI_STATUS_URL

                    # New users should leave this property as `true`, to identify the
                    # monitored entities as `remote`. Setting this property to `false` (the
                    # default value) is deprecated and will be removed soon, disallowing
                    # entities that are identified as `local`.
                    # Please check the documentation to get more information about local
                    # versus remote entities:
                    # https://github.com/newrelic/infra-integrations-sdk/blob/master/docs/entity-definition.md
                    remote_monitoring: true

              - name: apache-server-inventory
                command: inventory
                arguments:
                    status_url: $NR_CLI_STATUS_URL

                    # New users should leave this property as `true`, to identify the
                    # monitored entities as `remote`. Setting this property to `false` (the
                    # default value) is deprecated and will be removed soon, disallowing
                    # entities that are identified as `local`.
                    # Please check the documentation to get more information about local
                    # versus remote entities:
                    # https://github.com/newrelic/infra-integrations-sdk/blob/master/docs/entity-definition.md
                    remote_monitoring: true

          EOT

    restart:
      cmds:
        - sudo systemctl restart newrelic-infra.service
