name: apache-open-source-integration
displayName: Apache Open Source Integration
description: New Relic install recipe for default Apache Open Source on-host integration (via Infra-Agent)
repository: https://github.com/newrelic/nri-apache

dependencies:
  - infrastructure-agent-installer

observabilityPacks:
  - name: Apache
    level: NEWRELIC

installTargets:
  - type: host
    os: linux
    platform: amazon
    platformVersion: "2"
  - type: host
    os: linux
    platform: "centos"
  - type: host
    os: linux
    platform: "redhat"

# keyword convention for dealing with search terms that could land someone on this instrumentation project
keywords:
  - Infrastructure
  - Integration
  - apache

# Examine Infrastructure events for correlated data
processMatch:
  - httpd

# Matches partial list of the Log forwarding parameters
# https://docs.newrelic.com/docs/logs/enable-log-management-new-relic/enable-log-monitoring-new-relic/forward-your-logs-using-infrastructure-agent#parameters
logMatch:
  - name: apache
    file: /var/log/httpd/*access_log
  - name: apache error
    file: /var/log/httpd/*error_log

# NRQL the newrelic-cli will use to validate the agent/integration this recipe
# installed is successfully sending data to New Relic
validationNrql: "SELECT count(*) from ApacheSample where hostname like '{{.HOSTNAME}}%' FACET entityGuid SINCE 10 minutes ago"

preInstall:
  info: |2
      To capture data from the Apache integration, you'll first need to meet these prerequisites:
      - Apache version requirement (see https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/apache-monitoring-integration#comp-req)
      - Apache status module enabled and configured for Apache instance
      - Apache status module endpoint (default server-status) available

install:
  version: "3"
  silent: true

  tasks:
    default:
      cmds:
        - task: assert_infra
        - task: input_assert
          vars:
            MAX_RETRIES: 3
        - task: restart

    assert_infra:
      cmds:
        - |
          IS_INFRA_INSTALLED=$(sudo ps aux | grep newrelic-infra-service | grep -v grep | wc -l)
          if [ $IS_INFRA_INSTALLED -eq 0 ] ; then
            echo "The infrastructure agent is required to install this integration, we recommend going through our guided install path for this pre-requisite which can be found here:  https://docs.newrelic.com/docs/new-relic-guided-installation-overview" >&2
            exit 1
          fi

    input_assert:
      cmds:
        - |
          TRIES=0

          # Check Env Vars
          NEW_RELIC_ASSUME_YES="{{.NEW_RELIC_ASSUME_YES}}"
          NR_CLI_STATUS_URL="{{.NR_CLI_STATUS_URL}}"

          # Set Defaults
          NR_CLI_STATUS_URL=${NR_CLI_STATUS_URL:-'http://127.0.0.1/server-status?auto'}

          if [[ "$NEW_RELIC_ASSUME_YES" != "true" ]]; then
            while [ $TRIES -lt {{.MAX_RETRIES}} ]; do
              printf "\nApache status URL (default: http://127.0.0.1/server-status?auto): "
              read -r NR_CLI_STATUS_URL
              NR_CLI_STATUS_URL=${NR_CLI_STATUS_URL:-http://127.0.0.1/server-status?auto}
              ((TRIES++))

              code=$(curl -I $NR_CLI_STATUS_URL -w %{response_code} -so '/dev/null')
              if [ $code != "200" ]; then
                printf "\nApache status page is returning http error code $code. Apache must be correctly configured for New Relic to collect data. \n - See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/apache-monitoring-integration#config for more info.\n" >&2
                if [ ! $TRIES -lt {{.MAX_RETRIES}} ]; then exit 3; else continue; fi
                echo "Please try again"
                continue
              fi
              STUB_STATUS_ENABLED=$(curl $NR_CLI_STATUS_URL -s | grep "IdleWorkers:" | wc -l)
              if [ $STUB_STATUS_ENABLED -eq 0 ] ; then
                printf "\nStatus page is not returning expected data. Apache2 must be correctly configured for New Relic to collect data. \n - See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/apache-monitoring-integration#config for more info.\n" >&2
                if [ ! $TRIES -lt {{.MAX_RETRIES}} ]; then exit 2; else continue; fi
                echo "Please try again"
                continue
              fi
              break
            done
          fi
          printf "\n[OK] All checks passed. Installing Apache Integration...\n\n"

          sudo mkdir -p "/etc/newrelic-infra/integrations.d"
          sudo yum -q makecache -y --disablerepo='*' --enablerepo='newrelic-infra'
          sudo yum install nri-apache -y

          if [ -f /etc/newrelic-infra/integrations.d/apache-config.yml ]; then
            sudo rm /etc/newrelic-infra/integrations.d/apache-config.yml;
          fi
          sudo cp /etc/newrelic-infra/integrations.d/apache-config.yml.sample /etc/newrelic-infra/integrations.d/apache-config.yml;
          sudo tee /etc/newrelic-infra/integrations.d/apache-config.yml > /dev/null <<EOT
          integration_name: com.newrelic.apache

          instances:
              - name: apache-server-metrics
                command: metrics
                arguments:
                    status_url: $NR_CLI_STATUS_URL

                    # New users should leave this property as 'true', to identify the
                    # monitored entities as 'remote'. Setting this property to 'false' (the
                    # default value) is deprecated and will be removed soon, disallowing
                    # entities that are identified as 'local'.
                    # Please check the documentation to get more information about local
                    # versus remote entities:
                    # https://github.com/newrelic/infra-integrations-sdk/blob/master/docs/entity-definition.md
                    remote_monitoring: true

              - name: apache-server-inventory
                command: inventory
                arguments:
                    status_url: $NR_CLI_STATUS_URL

                    # New users should leave this property as 'true', to identify the
                    # monitored entities as 'remote'. Setting this property to 'false' (the
                    # default value) is deprecated and will be removed soon, disallowing
                    # entities that are identified as 'local'.
                    # Please check the documentation to get more information about local
                    # versus remote entities:
                    # https://github.com/newrelic/infra-integrations-sdk/blob/master/docs/entity-definition.md
                    remote_monitoring: true

          EOT

    restart:
      cmds:
        - |
          if [ {{.IS_SYSTEMCTL}} -gt 0 ]; then
            sudo systemctl restart newrelic-infra
          else 
            if [ {{.IS_INITCTL}} -gt 0 ]; then
              sudo initctl restart newrelic-infra
            else
              sudo /etc/init.d/newrelic-infra restart
            fi
          fi
      vars:
        IS_SYSTEMCTL:
          sh: command -v systemctl | wc -l
        IS_INITCTL:
          sh: command -v initctl | wc -l

postInstall:
  info: |2
      ⚙️  The Apache configuration file can be found in /etc/newrelic-infra/integrations.d/apache-config.yml
      Edit this file to make changes or configure advanced features for this integration. See the docs for options:
      https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/apache-monitoring-integration#config
