name: apache-open-source-integration
displayName: Apache Open Source Integration
description: New Relic install recipe for default Apache Open Source on-host integration (via Infra-Agent)
repository: https://github.com/newrelic/nri-apache

installTargets:
  - type: host
    os: linux
    platform: amazon
    platformVersion: "2"
  - type: host
    os: linux
    platform: "centos"
  - type: host
    os: linux
    platform: "redhat"

# keyword convention for dealing with search terms that could land someone on this instrumentation project
keywords:
  - Infrastructure
  - Integration
  - apache

# Examine Infrastructure events for correlated data
processMatch:
  - httpd

# Matches partial list of the Log forwarding parameters
# https://docs.newrelic.com/docs/logs/enable-log-management-new-relic/enable-log-monitoring-new-relic/forward-your-logs-using-infrastructure-agent#parameters
logMatch:
  - name: apache
    file: /var/log/httpd/*access_log
  - name: apache error
    file: /var/log/httpd/*error_log

# NRQL the newrelic-cli will use to validate the agent/integration this recipe
# installed is successfully sending data to New Relic
validationNrql: "SELECT count(*) from ApacheSample where hostname like '{{.HOSTNAME}}%' FACET entityGuid SINCE 10 minutes ago"

inputVars:
  - name: "NR_CLI_STATUS_URL"
    prompt: "Apache status URL (default: http://127.0.0.1/server-status?auto)"
    default: "http://127.0.0.1/server-status?auto"

preInstall:
  info: |2
      To capture data from the Apache integration, you'll first need to meet these prerequisites:
      - Apache versions 2.2 or 2.4
      - Apache status module enabled and configured for Apache instance
      - Apache status module endpoint (default server-status) available

install:
  version: "3"
  silent: true

  tasks:
    default:
      cmds:
        - task: assert_pre_req
        - task: setup
        - task: restart

    assert_pre_req:
      cmds:
        - |
          SERVICE_EXIST=$(sudo systemctl status newrelic-infra.service | grep "Active" | wc -l)
          if [ $SERVICE_EXIST -eq 0 ]; then
            echo "The newrelic-infra agent service is not installed on the host, but is required to install this integration." >> /dev/stderr
            exit 1
          fi
        - |
          STUB_STATUS_ENABLED=$(curl {{.NR_CLI_STATUS_URL}} -s | grep "IdleWorkers:" | wc -l)
          if [ $STUB_STATUS_ENABLED -eq 0 ] ; then
            echo "Status page is not returning data. Apache2 must be correctly configured for New Relic to collect data. \n - See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/apache-monitoring-integration#config for more info." >> /dev/stderr
            exit 2
          fi

    setup:
      label: "Installing Apache integration..."
      cmds:
        - |
          sudo mkdir -p "/etc/newrelic-infra/integrations.d"
        - |
          sudo yum update -y
        - |
          sudo yum install nri-apache -y
        - |
          if [ -f /etc/newrelic-infra/integrations.d/apache-config.yml ]; then
            sudo rm /etc/newrelic-infra/integrations.d/apache-config.yml;
          fi

          sudo cp /etc/newrelic-infra/integrations.d/apache-config.yml.sample /etc/newrelic-infra/integrations.d/apache-config.yml;

        - |
          sudo tee /etc/newrelic-infra/integrations.d/apache-config.yml > /dev/null <<"EOT"
          integration_name: com.newrelic.apache

          instances:
              - name: apache-server-metrics
                command: metrics
                arguments:
                    status_url: {{.NR_CLI_STATUS_URL}}
                    remote_monitoring: true
              - name: apache-server-inventory
                command: inventory
                arguments:
                    status_url: {{.NR_CLI_STATUS_URL}}
                    remote_monitoring: true

          EOT

    restart:
      cmds:
        - sudo systemctl restart newrelic-infra.service
