name: apache-open-source-integration
displayName: Apache Integration
description: New Relic install recipe for default Apache Open Source on-host integration (via Infra-Agent)
repository: https://github.com/newrelic/nri-apache

dependencies:
  - infrastructure-agent-installer

installTargets:
  - type: host
    os: linux
    platform: amazon
    platformVersion: "2"
    kernelArch: x86_64
  - type: host
    os: linux
    platform: "centos"
    kernelArch: x86_64
  - type: host
    os: linux
    platform: "redhat"
    kernelArch: x86_64

# keyword convention for dealing with search terms that could land someone on this instrumentation project
keywords:
  - Infrastructure
  - Integration
  - apache

# Examine Infrastructure events for correlated data
processMatch:
  - httpd

# Matches partial list of the Log forwarding parameters
# https://docs.newrelic.com/docs/logs/enable-log-management-new-relic/enable-log-monitoring-new-relic/forward-your-logs-using-infrastructure-agent#parameters
logMatch:
  - name: apache
    file: /var/log/httpd/*access_log
  - name: apache error
    file: /var/log/httpd/*error_log

# The newrelic-cli will use this integration name to check the config file(s)
# that were setup during the installation to ensure the integration
# runs properly with the defined environment variables
validationIntegration: apache

# DEPRECATED
validationNrql: "SELECT count(*) from ApacheSample FACET entityGuid SINCE 10 minutes ago WHERE reportingAgent = '{{.INFRA_KEY}}'"

preInstall:
  info: |2
      To capture data from the Apache integration, you'll first need to meet these prerequisites:
      - Apache version requirement (see https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/apache-monitoring-integration#comp-req)
      - Apache status module enabled and configured for Apache instance
      - Apache status module endpoint (default server-status) available
  requireAtDiscovery: |
    # Set Defaults
    NEW_RELIC_APACHE_STATUS_URL=${NEW_RELIC_APACHE_STATUS_URL:-${NR_CLI_STATUS_URL:-'http://127.0.0.1/server-status?auto'}}
    STUB_STATUS_ENABLED=$(curl $NEW_RELIC_APACHE_STATUS_URL -s | grep -i "idle" | wc -l)
    if [ $STUB_STATUS_ENABLED -gt 0 ] ; then
      # Supported case
      exit 0
    fi
    STUB_STATUS_IN_USE=$(httpd -t -D DUMP_INCLUDES | grep '/' | awk '{ print $2 }' | xargs grep '/server-status' | wc -l)
    if [ $STUB_STATUS_IN_USE -gt 0 ] ; then
      #Stub status page is enabled and in use, but not accessible from local machine
      exit 132
    fi
    if [ ! -f /etc/httpd/conf.d/server-status.conf ]; then
      # Can may be fix by setting up server status module
      exit 0
    fi
    exit 132

install:

  version: "3"
  silent: true

  tasks:
    default:
      cmds:
        - task: assert_infra
        - task: input_assert
        - task: restart

    assert_infra:
      cmds:
        - |
          IS_INFRA_INSTALLED=$(sudo ps aux | grep newrelic-infra-service | grep -v grep | wc -l)
          if [ $IS_INFRA_INSTALLED -eq 0 ] ; then
            echo "The infrastructure agent is required to install this integration, we recommend going through our guided install path for this pre-requisite which can be found here:  https://docs.newrelic.com/docs/full-stack-observability/observe-everything/get-started/new-relic-guided-install-overview" >&2
            exit 1
          fi

    input_assert:
      cmds:
        - |
          # Set Defaults
          NEW_RELIC_APACHE_STATUS_URL=${NEW_RELIC_APACHE_STATUS_URL:-${NR_CLI_STATUS_URL:-'http://127.0.0.1/server-status?auto'}}
          STUB_STATUS_ENABLED=$(curl $NEW_RELIC_APACHE_STATUS_URL -s | grep -i "idle" | wc -l)
          if [ $STUB_STATUS_ENABLED -eq 0 ] ; then
            if [ -f /etc/httpd/conf.d/server-status.conf ]; then
              printf "\nThe status page is not returning expected data. Apache must be configured with the server-status module for New Relic to collect data. \n - See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/apache-monitoring-integration#config for more info.\n" >&2
              exit 131
            fi
            if [ ! -d /etc/httpd/conf.d ]; then
              printf "\nThe server-status module is required in order to instrument Apache. \n - See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/apache-monitoring-integration#config for more info.\n" >&2
              exit 131
            fi
            echo "The server-status module is currently not enabled."
            echo "This installation would like to enable this module by creating this file /etc/httpd/conf.d/server-status.conf with this content:"
            echo '<Location "/server-status">'
            echo "  SetHandler server-status"
            echo "  Require local"
            echo "</Location>"
            echo "Apache is also going to be restarted in order for the new configuration to take effect."
            NEW_RELIC_ASSUME_YES="{{.NEW_RELIC_ASSUME_YES}}"
            if [[ "$NEW_RELIC_ASSUME_YES" != "true" ]]; then
              while :; do
                echo -n "Please confirm Y/N (default: Y)? "
                read answer
                echo ""
                NEW_RELIC_CONTINUE=$(echo "${answer^^}" | cut -c1-1)
                if [[ -z "$NEW_RELIC_CONTINUE" ]]; then
                  NEW_RELIC_CONTINUE="Y"
                fi
                if [[ "$NEW_RELIC_CONTINUE" == "N" ]]; then
                  echo "Exiting the installation"
                  exit 130
                fi
                if [[ "$NEW_RELIC_CONTINUE" == "Y" ]]; then
                  break
                fi
                echo -e "Please type Y or N only."
              done
            fi
            sudo tee -a /etc/httpd/conf.d/server-status.conf > /dev/null <<"EOT"
          <Location "/server-status">
            SetHandler server-status
            Require local
          </Location>
          EOT
            sudo systemctl restart httpd
            sleep 5
            NEW_RELIC_APACHE_STATUS_URL=${NEW_RELIC_APACHE_STATUS_URL:-${NR_CLI_STATUS_URL:-'http://127.0.0.1/server-status?auto'}}
            STUB_STATUS_ENABLED=$(curl $NEW_RELIC_APACHE_STATUS_URL -s | grep -i "idle" | wc -l)
            if [ $STUB_STATUS_ENABLED -eq 0 ] ; then
              printf "\nThe status page is not returning any data. Apache must be configured with the server-status module for New Relic to collect data. \n - See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/apache-monitoring-integration#config for more info.\n" >&2
              exit 131
            fi
          fi

          sudo mkdir -p "/etc/newrelic-infra/integrations.d"
          sudo yum -q makecache -y --disablerepo='*' --enablerepo='newrelic-infra'
          sudo yum install nri-apache -y

          if [ -f /etc/newrelic-infra/integrations.d/apache-config.yml ]; then
            sudo rm /etc/newrelic-infra/integrations.d/apache-config.yml;
          fi
          sudo cp /etc/newrelic-infra/integrations.d/apache-config.yml.sample /etc/newrelic-infra/integrations.d/apache-config.yml;
          sudo tee /etc/newrelic-infra/integrations.d/apache-config.yml > /dev/null <<EOT
          integrations:
            - name: nri-apache
              env:
                METRICS: true
                STATUS_URL: $NEW_RELIC_APACHE_STATUS_URL

                # New users should leave this property as 'true', to identify the
                # monitored entities as 'remote'. Setting this property to 'false' (the
                # default value) is deprecated and will be removed soon, disallowing
                # entities that are identified as 'local'.
                # Please check the documentation to get more information about local
                # versus remote entities:
                # https://github.com/newrelic/infra-integrations-sdk/blob/master/docs/entity-definition.md
                REMOTE_MONITORING: true
              interval: 15s

            - name: nri-apache
              env:
                INVENTORY: true
                STATUS_URL: $NEW_RELIC_APACHE_STATUS_URL

                # New users should leave this property as 'true', to identify the
                # monitored entities as 'remote'. Setting this property to 'false' (the
                # default value) is deprecated and will be removed soon, disallowing
                # entities that are identified as 'local'.
                # Please check the documentation to get more information about local
                # versus remote entities:
                # https://github.com/newrelic/infra-integrations-sdk/blob/master/docs/entity-definition.md
                REMOTE_MONITORING: true
              inventory_source: config/apache
              interval: 60s

          EOT

    restart:
      cmds:
        - |
          if [ {{.IS_SYSTEMCTL}} -gt 0 ]; then
            sudo systemctl restart newrelic-infra
          else 
            if [ {{.IS_INITCTL}} -gt 0 ]; then
              sudo initctl restart newrelic-infra
            else
              sudo /etc/init.d/newrelic-infra restart
            fi
          fi
      vars:
        IS_SYSTEMCTL:
          sh: command -v systemctl | wc -l
        IS_INITCTL:
          sh: command -v initctl | wc -l

postInstall:
  info: |2
      ⚙️  The Apache configuration file can be found in /etc/newrelic-infra/integrations.d/apache-config.yml
      Edit this file to make changes or configure advanced features for this integration. See the docs for options:
      https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/apache-monitoring-integration#config
