name: aws-integration
displayName: AWS Integration
description: New Relic install recipe for AWS
repository: https://github.com/newrelic/newrelic-cli

installTargets:
  - type: host
    os: windows
    kernelArch: x86_64

keywords:
  - Ec2
  - Elastic
  - Compute
  - Aws
  - Cloud
  - Windows

processMatch: []

preInstall:
  requireAtDiscovery: |
      powershell -command '
        $code = ""
        try {
          $code=Invoke-WebRequest -Headers @{"X-aws-ec2-metadata-token-ttl-seconds" = "100"} -UseBasicParsing -Method PUT -TimeoutSec 1 -Uri http://169.254.169.254/latest/api/token | Select-Object -ExpandProperty StatusCode;
        } catch {}

        if ($code -ieq "200") {
          exit 132
        }

        exit 1
      '
  info: |2
      Amazon integrations let you monitor your AWS data in several New Relic features.

install:
  version: "3"
  silent: true

  tasks:
    default:
      cmds:
        - task: setup

    setup:
      cmds:
        - |
          exit 131

postInstall:
  info: |2
      ⚙️  The AWS integration has been installed.
      See the docs:
      https://docs.newrelic.com/docs/integrations/amazon-integrations/aws-integrations-list/aws-metric-stream/
