name: aws-integration
displayName: AWS Integration
description: New Relic install recipe for AWS
repository: https://github.com/newrelic/newrelic-cli

installTargets:
  - type: host
    os: linux

keywords:
  - Ec2
  - Elastic
  - Compute
  - Aws
  - Cloud
  - Linux

processMatch: []

preInstall:
  requireAtDiscovery: |
      code=$(curl -X PUT -H "X-aws-ec2-metadata-token-ttl-seconds: 100" -I "http://169.254.169.254/latest/api/token" -w %{response_code} -so '/dev/null')

      if [ $code != "200" ]; then
        exit 1
      fi

      if [ ! -f ~/.aws/credentials ]; then
        echo "The AWS user has not been configured" >&2
        exit 132
      fi

      if [ ! -f ~/.aws/config ]; then
        echo "The AWS default region has not been configured" >&2
        exit 132
      fi

      if ! command -v aws &> /dev/null; then
        echo "The AWS-cli could not be found" >&2
        exit 132
      fi

      callerIdentity=$(aws sts get-caller-identity 2>&1)

      wasAccessDenied=$(echo "$callerIdentity" | grep AccessDenied | wc -l)

      if [ "$wasAccessDenied" -eq 1 ]; then
        echo "The configured AWS user does not have an attached AdministratorAccess policy" >&2
        exit 132
      fi

      username=$(echo "$callerIdentity" | sed -ne 's/.*"Arn": ".*\/\(.*\)".*/\1/p')

      attachedUserPolicies=$(aws iam list-attached-user-policies --user-name $username 2>&1)

      wasAccessDenied=$(echo "$attachedUserPolicies" | grep AccessDenied | wc -l)

      if [ "$wasAccessDenied" -eq 1 ]; then
        echo "The configured AWS user does not have an attached AdministratorAccess policy" >&2
        exit 132
      fi

      hasAdminAccess=$(echo "$attachedUserPolicies" | grep AdministratorAccess | wc -l)

      if [ "$hasAdminAccess" -eq 0 ] ; then
        groups=$(aws iam list-groups-for-user --user-name $username 2>&1)

        # For each group in groups
        listOfGroups=$(echo "$groups" | sed -n 's/.*:group\/\(.*\)",.*/\1/p')

        for i in $listOfGroups; do
          groupPolicies=$(aws iam list-group-policies --group-name $i 2>&1)

          hasAdminAccess=$(echo "$groupPolicies" | grep AdministratorAccess | wc -l)

          if [ "$hasAdminAccess" -eq 1 ]; then
            break
          fi

          attachedGroupPolicies=$(aws iam list-attached-group-policies --group-name $i 2>&1)

          hasAdminAccess=$(echo "$attachedGroupPolicies" | grep AdministratorAccess | wc -l)

          if [ "$hasAdminAccess" -eq 1 ]; then
            break
          fi
        done
      fi

      if [ "$hasAdminAccess" -eq 0 ] ; then
        echo "The configured AWS user does not have an attached AdministratorAccess policy" >&2
        exit 132
      fi

      deployed=$(aws cloudformation describe-stacks --stack-name NewRelic-Metric-Stream 2>&1 | grep "^An error occurred (ValidationError)*" | wc -l)

      if [ "$deployed" -eq 0 ]; then
        echo "The NewRelic-Metric-Stream CloudformationStack is already deployed" >&2
        exit 1
      fi
  info: |2
      Amazon integrations let you monitor your AWS data in several New Relic features.

install:
  version: "3"
  silent: true

  tasks:
    default:
      cmds:
        - task: setup

    setup:
      cmds:
        - |
          # Constants
          roleName="NewRelicInfrastructure-Integrations"

          getRole=$(aws iam get-role --role-name $roleName 2>&1)

          if [ "$(echo "$getRole" | grep NoSuchEntity | wc -l)" -eq 1 ]; then
              policy=$(cat <<EOT
          {
              "Version": "2012-10-17",
              "Statement": [
                  {
                      "Sid": "",
                      "Effect": "Allow",
                      "Principal": {
                          "AWS": "arn:aws:iam::754728514883:root"
                      },
                      "Action": "sts:AssumeRole",
                      "Condition": {
                          "StringEquals": {
                              "sts:ExternalId": "{{.NEW_RELIC_ACCOUNT_ID}}"
                          }
                      }
                  }
              ]
          }
          EOT
              )

              createRole=$(aws iam create-role --role-name $roleName --assume-role-policy-document file://<(echo $policy) 2>&1)

              aws iam attach-role-policy --role-name $roleName --policy-arn arn:aws:iam::aws:policy/ReadOnlyAccess

              policy=$(cat <<EOT
          {
              "Version": "2012-10-17",
              "Statement": [
                  {
                  "Effect": "Allow",
                  "Action": [
                      "budgets:ViewBudget"
                  ],
                  "Resource": "*"
                  }
              ]
          }
          EOT
              )

              aws iam put-role-policy --role-name $roleName --policy-name NewRelicBudget --policy-document file://<(echo $policy)
          fi

          callerIdentity=$(aws sts get-caller-identity 2>&1)

          accountName=$(echo "$callerIdentity" | sed -ne 's/.*Account": "\(.*\)",/\1/p')

          # Download and fix CloudFormation template
          curl -sLo /tmp/MetricStreams_CloudFormation.yml {{.NEW_RELIC_DOWNLOAD_URL}}cloud_integrations/aws/cloudformation/MetricStreams_CloudFormation.yml
          sed -ie "s/AWS::AccountId,/\'AWS::AccountId\',/g" /tmp/MetricStreams_CloudFormation.yml

          printf "\nDeploying CloudFormation template, this may take a few minutes...\n"
          deploy=$(aws cloudformation deploy --template-file /tmp/MetricStreams_CloudFormation.yml --stack-name NewRelic-Metric-Stream --parameter-overrides NewRelicLicenseKey={{.NEW_RELIC_LICENSE_KEY}} --capabilities CAPABILITY_NAMED_IAM 2>&1)

          if [ "$(echo "$deploy" | grep "^An error occurred (AlreadyExistsException)*" | wc -l)" -eq 1 ]; then
              echo "CloudFormation stack already exists"
              rm /tmp/MetricStreams_CloudFormation.yml
              exit 0
          fi

          if [ "$(echo "$deploy" | grep "^An error occurred (InvalidChangeSetStatus)*" | wc -l)" -eq 1 ]; then
              echo "CloudFormation stack is already being deployed"
              rm /tmp/MetricStreams_CloudFormation.yml
              exit 0
          fi

          if [ "$(echo "$deploy" | grep "*CREATE_IN_PROGRESS*" | wc -l)" -eq 1 ]; then
              echo "CloudFormation stack is already being deployed"
              rm /tmp/MetricStreams_CloudFormation.yml
              exit 0
          fi

          echo "CloudFormation deployment complete"

          rm /tmp/MetricStreams_CloudFormation.yml

          getRole=$(aws iam get-role --role-name $roleName 2>&1)

          arn=$(echo $getRole | sed -ne 's/.*"Arn": "\(.*\)".*/\1/p')

          query=$(echo { \"query\": \"mutation { cloudLinkAccount\(accountId: {{.NEW_RELIC_ACCOUNT_ID}}, accounts: { aws: { name: \\\"$accountName\\\", arn: \\\"$arn\\\", metricCollectionMode: PUSH}}\) { linkedAccounts { id name authLabel createdAt updatedAt } } }\" })

          NEW_RELIC_API_URL='https://api.newrelic.com/graphql'

          if [ $(echo {{.NEW_RELIC_REGION}} | grep -i staging | wc -l) -gt 0 ]; then
            NEW_RELIC_API_URL='https://staging-api.newrelic.com/graphql'
          elif [ $(echo {{.NEW_RELIC_REGION}} | grep -i eu | wc -l) -gt 0 ]; then
            NEW_RELIC_API_URL='https://api.eu.newrelic.com/graphql'
          fi

          curlQuery=$(echo $query | curl $NEW_RELIC_API_URL \
          -H 'Content-Type: application/json' \
          -H 'API-Key: {{.NEW_RELIC_API_KEY}}' \
          -d @- 2>&1)

          echo "Your AWS and New Relic accounts are linked"

postInstall:
  info: |2
      ⚙️  The AWS integration has been installed.
      See the docs:
      https://docs.newrelic.com/docs/integrations/amazon-integrations/aws-integrations-list/aws-metric-stream/
