name: azure-integration
displayName: Microsoft Azure Integration
description: New Relic install recipe for Azure
repository: https://github.com/newrelic/newrelic-cli

installTargets:
  - type: host
    os: windows
    kernelArch: x86_64

keywords:
  - Virtual
  - Machine
  - Azure
  - Cloud
  - Windows

processMatch: []

preInstall:
  requireAtDiscovery: |
      powershell -command '
        $code = ""
        try {
          $code=Invoke-WebRequest -Headers @{"Metadata"="true"} -UseBasicParsing -Method Get -TimeoutSec 1 -Uri "http://169.254.169.254/metadata/instance/compute/vmId?api-version=2021-11-01&format=text" | Select-Object -ExpandProperty StatusCode;
        } catch {}

        if ($code -ieq "200") {
          exit 132
        }

        exit 1
      '
  info: |2
      The Microsoft Azure integrations report data from various Azure platform services to your New Relic account.

install:
  version: "3"
  silent: true

  tasks:
    default:
      cmds:
        - task: setup

    setup:
      cmds:
        - |
          exit 131

postInstall:
  info: |2
      ⚙️  The Azure integration has been installed.
      See the docs:
      https://docs.newrelic.com/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-vms-monitoring-integration/
