name: azure-integration
displayName: Microsoft Azure Integration
description: New Relic install recipe for Azure
repository: https://github.com/newrelic/newrelic-cli

installTargets:
  - type: host
    os: linux

keywords:
  - Virtual
  - Machine
  - Azure
  - Cloud
  - Linux

preInstall:
  requireAtDiscovery: |
      code=$(curl -I http://169.254.169.254/metadata/instance/compute/vmId -w %{response_code} -so '/dev/null')
      if [ $code == "200" ]; then
        exit 132
      fi
      exit 1
  info: |2
      The Microsoft Azure integrations report data from various Azure platform services to your New Relic account.

install:
  version: "3"
  silent: true

  tasks:
    default:
      cmds:
        - task: setup

    setup:
      cmds:
        - |
          exit 0

postInstall:
  info: |2
      ⚙️  The Azure integration has been installed.
      See the docs:
      https://docs.newrelic.com/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-vms-monitoring-integration/
