name: gcp-integration
displayName: Google Cloud Platform Integration
description: New Relic install recipe for GCP
repository: https://github.com/newrelic/newrelic-cli

installTargets:
  - type: host
    os: linux

keywords:
  - Compute
  - Engine
  - Gcp
  - Cloud
  - Linux

processMatch: []

preInstall:
  requireAtDiscovery: |
      code=$(curl -H "Metadata-Flavor: Google" --connect-timeout 2 --max-time 2 'http://169.254.169.254/computeMetadata/v1/instance/id' -w %{response_code} -so '/dev/null')
      if [ $code == "200" ]; then
        exit 132
      fi
      exit 1
  info: |2
      New Relic's Google Cloud Platform (GCP) integrations let you monitor your GCP data in several New Relic features.

install:
  version: "3"
  silent: true

  tasks:
    default:
      cmds:
        - task: setup

    setup:
      cmds:
        - |
          exit 131

postInstall:
  info: |2
      ⚙️  The GCP integration has been installed.
      See the docs:
      https://docs.newrelic.com/docs/infrastructure/google-cloud-platform-integrations/gcp-integrations-list/google-compute-engine-monitoring-integration/
