name: gcp-integration
displayName: Google Cloud Platform Integration
description: New Relic install recipe for GCP
repository: https://github.com/newrelic/newrelic-cli

installTargets:
  - type: host
    os: windows
    kernelArch: x86_64

keywords:
  - Compute
  - Engine
  - Gcp
  - Cloud
  - Windows

preInstall:
  requireAtDiscovery: |
      $code = ""
      try {
        $code=Invoke-WebRequest -UseBasicParsing -Method Get -TimeoutSec 1 -Uri http://169.254.169.254/computeMetadata/v1/instance/id -ContentType "Metadata-Flavor: Google" | Select-Object -ExpandProperty StatusCode;
      } catch {}

      if ($code -ieq "200") {
        exit 132
      }

      exit 1
  info: |2
      New Relic's Google Cloud Platform (GCP) integrations let you monitor your GCP data in several New Relic features.

install:
  version: "3"
  silent: true

  tasks:
    default:
      cmds:
        - task: setup

    setup:
      cmds:
        - |
          exit 131

postInstall:
  info: |2
      ⚙️  The GCP integration has been installed.
      See the docs:
      https://docs.newrelic.com/docs/infrastructure/google-cloud-platform-integrations/gcp-integrations-list/google-compute-engine-monitoring-integration/
