# Visit our schema definition for additional information on this file format.
# https://github.com/newrelic/open-install-library/blob/main/docs/recipe-spec/recipe-spec.md#schema-definition

name: infrastructure-agent-installer
displayName: Infrastructure Agent
description: New Relic install recipe for the Infrastructure agent
repository: https://github.com/newrelic/infrastructure-agent

installTargets:
  - type: host
    os: darwin

keywords:
  - Infrastructure
  - Agent
  - Darwin
  - Macos

processMatch: []

validationUrl: "http://localhost:18003/v1/status/entity"

install:
  version: "3"
  silent: true

  vars:
    CONFIG_FILE: "/usr/local/etc/newrelic-infra/newrelic-infra.yml"
    CONFIG_FILE_DIR: "/usr/local/etc/newrelic-infra"
    ARROW: '\033[0;36m===> \033[0;97m'

  tasks:
    default:
      cmds:
        - task: assert_pre_req
        - task: cleanup
        - task: setup_license
        - task: setup_proxy
        - task: install_infra
        - task: restart
        - task: assert_agent_started
        - task: assert_agent_status_ok

    assert_pre_req:
      cmds:
        - |
          IS_ROOT_OR_SUDO=$([ ! -z "$SUDO_USER"] || [ $(whoami) = "root" ] && echo "true" || echo "false") # Assert root or sudo user
          if [ "$IS_ROOT_OR_SUDO" = "false" ]; then
            echo "recipe needs to be run with sudo. Please re-run the installation with sudo or root." >&2
            exit 7
          fi
        - |
          IS_GREP_INSTALLED=$(which grep | wc -l)
          if [ $IS_GREP_INSTALLED -eq 0 ] ; then
            echo "grep is required to run the newrelic install. Please install grep and re-run the installation." >&2
            exit 10
          fi
        - |
          IS_SED_INSTALLED=$(which sed | wc -l)
          if [ $IS_SED_INSTALLED -eq 0 ] ; then
            echo "sed is required to run the newrelic install. Please install sed and re-run the installation." >&2
            exit 11
          fi
        - |
          IS_TOUCH_INSTALLED=$(which touch | wc -l)
          if [ $IS_TOUCH_INSTALLED -eq 0 ] ; then
            echo "touch is required to run the newrelic install. Please install touch and re-run the installation." >&2
            exit 15
          fi
        - |
          IS_BREW_INSTALLED=$(which brew | wc -l)
          if [ $IS_BREW_INSTALLED -eq 0 ] ; then
            while :; do
              echo -n "brew is required to run the newrelic install. Do you want to install it? Y/N (default: Y) "
              read answer
              echo ""
              NEW_RELIC_CONTINUE=$(echo "${answer^^}" | cut -c1-1)
              if [[ -z "$NEW_RELIC_CONTINUE" ]]; then
                NEW_RELIC_CONTINUE="Y"
              fi
              if [[ "$NEW_RELIC_CONTINUE" == "N" ]]; then
                echo "brew is required to run the newrelic install. Please install brew and re-run the installation." >&2
                exit 131
              fi
              if [[ "$NEW_RELIC_CONTINUE" == "Y" ]]; then
                break
              fi
              echo -e "Please type Y or N only."
            done
            echo -e "{{.ARROW}}Installing brew...{{.GRAY}}"
            echo ""
            BREW_INSTALL_SUCCESS=$(/bin/bash -c 'curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | bash > /dev/null 2>&1; echo $?')
            if [ "$BREW_INSTALL_SUCCESS" -gt 0 ]; then
              echo "brew install failed. Try to install it manually following instructions in https://brew.sh and re-run the installation."
              exit 16
            fi
          fi
        - |
          IS_CURL_INSTALLED=$(which curl | wc -l)
          if [ $IS_CURL_INSTALLED -eq 0 ] ; then
            echo "curl is required to run the newrelic install. Please install curl and re-run the installation." >&2
            exit 17
          fi

    cleanup:
      cmds:
        - |
          rm -rf "/usr/local/var/db/newrelic-infra/data"

    setup_license:
      cmds:
        - |
          if [ -f "{{.CONFIG_FILE}}" ]; then
            sed -i.bak "/^staging/d" "{{.CONFIG_FILE}}" && rm "{{.CONFIG_FILE}}".bak
            sed -i.bak "/^enable_process_metrics/d" "{{.CONFIG_FILE}}" && rm "{{.CONFIG_FILE}}".bak
            sed -i.bak "/^status_server_enabled/d" "{{.CONFIG_FILE}}" && rm "{{.CONFIG_FILE}}".bak
            sed -i.bak "/^status_server_port/d" "{{.CONFIG_FILE}}" && rm "{{.CONFIG_FILE}}".bak
            sed -i.bak "/^license_key/d" "{{.CONFIG_FILE}}" && rm "{{.CONFIG_FILE}}".bak
            sed -i.bak "/^metrics_process_sample_rate/d" "{{.CONFIG_FILE}}" && rm "{{.CONFIG_FILE}}".bak
          else
            mkdir -p "{{.CONFIG_FILE_DIR}}"
            touch "{{.CONFIG_FILE}}"
          fi
        - |
          if [ $(echo {{.NEW_RELIC_REGION}} | grep -i staging | wc -l) -gt 0 ]; then
            echo 'staging: true' >> "{{.CONFIG_FILE}}"
          fi
          echo 'enable_process_metrics: true' >> "{{.CONFIG_FILE}}"
          echo 'status_server_enabled: true' >> "{{.CONFIG_FILE}}"
          echo 'status_server_port: 18003' >> "{{.CONFIG_FILE}}"
          echo 'license_key: {{.NEW_RELIC_LICENSE_KEY}}' >> "{{.CONFIG_FILE}}"

    setup_proxy:
      cmds:
        - |
          if [ ! -z "$HTTPS_PROXY" ]; then
            sed -i.bak "/^proxy/d" "{{.CONFIG_FILE}}" && rm "{{.CONFIG_FILE}}".bak
            echo 'proxy: {{.HTTPS_PROXY}}' >> "{{.CONFIG_FILE}}"
          fi

    install_infra:
      cmds:
        - |
          brew install newrelic-infra-agent -q

    restart:
      cmds:
        - |
          brew services restart newrelic-infra-agent

    assert_agent_started:
      cmds:
        - |
          # Ensure agent has enough time to start
          sleep 10
          IS_INFRA_INSTALLED=$(ps aux | grep newrelic-infra-service | grep -v grep | wc -l)
          if [ $IS_INFRA_INSTALLED -eq 0 ] ; then
            echo "The infrastructure agent has not started after installing. Please try again later, or see our documentation for installing manually https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/install-configure/install-new-relic" >&2
            exit 31
          fi

    assert_agent_status_ok:
      cmds:
        - |
          MAX_RETRIES=30
          TRIES=0
          echo "Running agent status check attempt..."
          # wait for status endpoint to be ready
          while [ $TRIES -lt $MAX_RETRIES ]; do
            ((TRIES++))
            statusCheckOutput=$(curl http://localhost:18003/v1/status/errors -s)
            if [ "$statusCheckOutput" == "{}" ]; then
              echo "Agent status check ok."
              break
            else
              if [ "$statusCheckOutput" == "" ]; then
                if [ "$TRIES" -eq "$MAX_RETRIES" ]; then
                  echo "infra-agent status endpoint not available" >&2
                  exit 32
                fi
              else
                if [ "$TRIES" -eq "$MAX_RETRIES" ]; then
                  echo "infra-agent status check not healthy: $statusCheckOutput" >&2
                  exit 33
                fi
              fi
            fi

            sleep 2
          done

postInstall:
  info: |2
      ⚙️  The Infrastructure Agent configuration file can be found in /usr/local/etc/newrelic-infra/newrelic-infra.yml
      Edit this file to make changes or configure advanced features for the agent. See the docs for options:
      https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings
      
      Note: Process monitoring has been enabled by default - all other config options are left to the user.
