# Visit our schema definition for additional information on this file format
# https://github.com/newrelic/open-install-library/blob/main/docs/recipe-spec/recipe-spec.md#schema-definition

name: infrastructure-agent-installer
displayName: Infrastructure Agent Installer
description: New Relic install recipe for the Infrastructure agent
repository: https://github.com/newrelic/infrastructure-agent

installTargets:
  - type: host
    os: linux
    platform: "debian"

keywords:
  - Infrastructure
  - Agent
  - Linux
  - Debian
  - Jessie
  - Stretch
  - Buster

processMatch:
  - /infra/

validationNrql: "SELECT count(*) from SystemSample where hostname like '{{.HOSTNAME}}' FACET entityGuid SINCE 10 minutes ago"

install:

  version: "3"
  silent: true

  tasks:
    default:
      cmds:
        - task: setup_license
        - task: install_infra

    setup_license:
      cmds:
        - |
          if [ -f /etc/newrelic-infra.yml ]; then
            sudo rm /etc/newrelic-infra.yml;
          fi
          sudo touch /etc/newrelic-infra.yml;
        - |
          grep -q '^license_key' /etc/newrelic-infra.yml && sudo sed -i 's/^license_key.*/license_key: {{.NEW_RELIC_LICENSE_KEY}}/' /etc/newrelic-infra.yml || echo 'license_key: {{.NEW_RELIC_LICENSE_KEY}}' | sudo tee -a /etc/newrelic-infra.yml > /dev/null
        - |
          if [ $(echo {{.NEW_RELIC_REGION}} | grep -i staging | wc -l) -gt 0 ]; then
            echo 'staging: true' | sudo tee -a /etc/newrelic-infra.yml > /dev/null
          fi

    install_infra:
      cmds:
        - sudo apt-get update
        - sudo apt-get install gnupg2 -y
        - sudo curl -s https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg | sudo apt-key add -
        - printf "deb [arch=amd64] https://download.newrelic.com/infrastructure_agent/linux/apt {{.DEBIAN_CODENAME}} main" | sudo tee -a /etc/apt/sources.list.d/newrelic-infra.list > /dev/null
        - sudo apt-get update
        - sudo apt-get install newrelic-infra -y
        - echo "New Relic infrastructure agent installed for Debian {{.DEBIAN_CODENAME}}"
      vars:
        DEBIAN_CODENAME:
          sh: cat /etc/os-release | grep VERSION_CODENAME | awk -F = '{print $2}'
      silent: true

