# Visit our schema definition for additional information on this file format
# https://github.com/newrelic/open-install-library/blob/main/docs/recipe-spec/recipe-spec.md#schema-definition

name: infrastructure-agent-installer
displayName: Infrastructure Agent
description: New Relic install recipe for the Infrastructure agent
repository: https://github.com/newrelic/infrastructure-agent

installTargets:
  - type: host
    os: linux
    platform: "ubuntu"

keywords:
  - Infrastructure
  - Agent
  - Linux
  - Ubuntu
  - Precise
  - Trusty
  - Xenial
  - Bionic
  - Focal

processMatch: []

validationNrql: "SELECT count(*) from SystemSample where hostname like '{{.HOSTNAME}}' FACET entityGuid SINCE 10 minutes ago"

install:
  version: "3"
  silent: true

  tasks:
    default:
      cmds:
        - task: setup_license
        - task: install_infra
        - task: restart

    setup_license:
      cmds:
        - |
          if [ -f /etc/newrelic-infra.yml ]; then
            sudo rm /etc/newrelic-infra.yml;
          fi
          sudo touch /etc/newrelic-infra.yml;
        - |
          sudo tee /etc/newrelic-infra.yml > /dev/null <<"EOT"
          license_key: {{.NEW_RELIC_LICENSE_KEY}}
          enable_process_metrics: true
          EOT
        - |
          if [ $(echo {{.NEW_RELIC_REGION}} | grep -i staging | wc -l) -gt 0 ]; then
            echo 'staging: true' | sudo tee -a /etc/newrelic-infra.yml > /dev/null
          fi

    install_infra:
      cmds:
        - sudo curl -s https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg | sudo apt-key add -
        - sudo rm -f /etc/apt/sources.list.d/newrelic-infra.list
        - printf "deb [arch=amd64] https://download.newrelic.com/infrastructure_agent/linux/apt {{.DISTRIB_CODENAME}} main" | sudo tee -a /etc/apt/sources.list.d/newrelic-infra.list > /dev/null
        - sudo apt-get update -qq
        - sudo apt-get install newrelic-infra -y -qq
      vars:
        DISTRIB_CODENAME:
          sh: cat /etc/lsb-release | grep DISTRIB_CODENAME | awk -F = '{print $2}'
      silent: true

    restart:
      cmds:
        - sudo systemctl restart newrelic-infra.service

postInstall:
  info: |2
      ⚙️  The Infrastructure Agent configuration file can be found in /etc/newrelic-infra.yml
      Edit this file to make changes or configure advanced features for the agent. See the docs for options:
      https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings
      
      Note: Process monitoring has been enabled by default - all other config options are left to the user.
