# Visit our schema definition for additional information on this file format
# https://github.com/newrelic/open-install-library/blob/main/docs/recipe-spec/recipe-spec.md#schema-definition

name: infrastructure-agent-installer
displayName: Infrastructure Agent Installer
description: New Relic install recipe for the Infrastructure agent on Windows
repository: https://github.com/newrelic/infrastructure-agent

installTargets:
  - type: host
    os: windows

keywords:
  - Infrastructure
  - Agent
  - Windows

processMatch: []

validationNrql: "SELECT count(*) from SystemSample where hostname like '{{.HOSTNAME}}' FACET entityGuid SINCE 10 minutes ago"

install:

  version: "3"
  silent: true

  tasks:
    default:
      cmds:
        - task: remove_any_previous
        - task: install

    remove_any_previous:
      ignore_error: true
      cmds:
        - powershell -command 'net stop newrelic-infra'
        - powershell -command '$app = Get-WmiObject -Class Win32_Product -Filter "Name = 'New Relic Infrastructure Agent'"; $app.Uninstall()'

    install:
      cmds:
        - powershell -command '(New-Object System.Net.WebClient).DownloadFile("https://download.newrelic.com/infrastructure_agent/windows/newrelic-infra.msi", "$env:TEMP\newrelic-infra.msi");'
        - powershell -command '$LICENSE_KEY="{{.NEW_RELIC_LICENSE_KEY}}"; msiexec.exe /qn /i "$env:TEMP\newrelic-infra.msi" GENERATE_CONFIG=true LICENSE_KEY="$LICENSE_KEY" | Out-Null;'
        - powershell -command '(New-Object System.Net.WebClient).DownloadFile("https://aka.ms/vs/16/release/vc_redist.x64.exe", "$env:TEMP\vc_redist.x64.exe");'
        - powershell -command 'start-process -FilePath "$env:TEMP\vc_redist.x64.exe" -ArgumentList "/install /q /norestart" -Verb RunAs -wait | Out-Null;'
        - powershell -command '$NEW_RELIC_REGION="{{.NEW_RELIC_REGION}}"; if ($NEW_RELIC_REGION -ilike "staging") { Add-Content -Path "C:\\Program Files\\New Relic\\newrelic-infra\\newrelic-infra.yml" -Value "staging`:` true" -Force; };'
        - powershell -command '$logs = "C:\\Program Files\\New Relic\\newrelic-infra\\logging.d\\logs.yml"; if (Test-Path $logs) { Remove-Item $logs }'
        - powershell -command 'echo "{{.LOGS_CONTENT}}" >> "C:\\Program Files\\New Relic\\newrelic-infra\\logging.d\\logs.yml"'
        - powershell -command 'net start newrelic-infra'
        - echo "New Relic infrastructure agent for Windows installed and started"
      vars:
        LOGS_CONTENT: |
          logs:
            - name: windows-security
              winlog:
                channel: Security
                collect-eventids:
                - 4740
                - 4728
                - 4732
                - 4756
                - 4735
                - 4624
                - 4625
                - 4648

            - name: windows-application
              winlog:
                channel: Application
