# Visit our schema definition for additional information on this file format.
# https://github.com/newrelic/open-install-library/blob/main/docs/recipe-spec/recipe-spec.md#schema-definition

name: infrastructure-agent-installer
displayName: Infrastructure Agent
description: New Relic install recipe for the Infrastructure agent on Windows
repository: https://github.com/newrelic/infrastructure-agent

installTargets:
  - type: host
    os: windows

keywords:
  - Infrastructure
  - Agent
  - Windows

processMatch: []

# DEPRECATED! Use `validationUrl` instead.
validationNrql: "SELECT count(*) from SystemSample where hostname like '{{.HOSTNAME}}' FACET entityGuid SINCE 5 minutes ago"
validationUrl: "http://localhost:18003/v1/status/entity"

preInstall:
  requireAtDiscovery: |
    powershell -command '
    # Checking docker
    $foundService = Get-Service -Name cexecsvc -ErrorAction SilentlyContinue
    if($foundService.Length -gt 0) {
      exit 131
    }
    exit 0
    '

install:
  version: "3"
  silent: true

  tasks:
    default:
      cmds:
        - task: assert_required_permissions
        - task: assert_required_powershell
        - task: collect_meta
        - task: remove_any_previous
        - task: download_infra
        - task: install_infra
        - task: start_infra
        - task: assert_agent_status_ok

    assert_required_permissions:
      cmds:
        - |
          powershell -command '
          $currentPrincipal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
          $isAdmin = $currentPrincipal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)


          if(-not ($isAdmin))
          {
            Write-Host -ForegroundColor Red "Powershell needs to be started in Administrator permissions. Please restart Powershell in Administrator, and re-run the newrelic-cli command."
            exit 131;
          }
          '

    assert_required_powershell:
      cmds:
        - |
          powershell -command '
          $powershellEnabled = ""
          try {
            $powershellEnabled = Get-Command -All powershell.exe | select Name
          }
          catch { }
          if ($powershellEnabled.Name -ne "powershell.exe") {
            Write-Host -ForegroundColor Red "Powershell is required. Please start Powershell in Administrator, and re-run the newrelic-cli command."
            exit 131;
          }
          '

    remove_any_previous:
      ignore_error: true
      cmds:
        - |
          powershell -command '
          try{
            if ( Get-Service "newrelic-infra" -ErrorAction SilentlyContinue) {
              Stop-Service -Name "newrelic-infra" -Force -PassThru | Out-Null
            }
            function Find-UninstallGuids {
              param (
                [Parameter(Mandatory)]
                [string]$Match
              )

              $baseKeys = Get-ChildItem -Path HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall `
              | % { $_.Name.TrimStart("HKEY_LOCAL_MACHINE\") }

              $wowKeys = Get-ChildItem -Path HKLM:\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall `
              | % { $_.Name.TrimStart("HKEY_LOCAL_MACHINE\") }

              $allKeys = $baseKeys + $wowKeys

              $uninstallIds = New-Object System.Collections.ArrayList
              foreach ($key in $allKeys) {
                $keyData = Get-Item -Path HKLM:\$key
                $name = $keyData.GetValue("DisplayName")
                if ($name -and $name -match $Match) {
                  $keyId = Split-Path $key -Leaf
                  $uninstallIds.Add($keyId) | Out-Null
                }
              }

              if ($uninstallIds.Count -eq 0) {
                return @()
              }

              return $uninstallIds
            }

            $uninstallIds = Find-UninstallGuids -Match "New Relic Infrastructure Agent"
            foreach ($uninstallId in $uninstallIds) {
              $uninstallCommand = "msiexec /x """ + $uninstallId + """ /qn"
              $er = (Invoke-Expression $uninstallCommand) 2>&1
              if($er.Exception){
                throw $er.Exception
              }
              # wait here to allow uninstall command to complete since it returns without waiting
              Start-Sleep -s 15
            }
          }
          catch {
            Write-Host -ForegroundColor Red "We detected you may be running an anti-virus software preventing our installation to continue. Please check your anti-virus software to allow Powershell execution while running this installation."
            exit 131;
          }
          '

    download_infra:
      cmds:
        - |
          powershell -command '
          try {
            [Net.ServicePointManager]::SecurityProtocol = "tls";
            [Net.ServicePointManager]::SecurityProtocol = "tls12, tls";
            [Net.ServicePointManager]::SecurityProtocol = "tls13, tls12, tls"
          }
          catch {}

          try {
            (New-Object System.Net.WebClient).DownloadFile("{{.NEW_RELIC_DOWNLOAD_URL}}infrastructure_agent/windows/newrelic-infra.msi", "$env:TEMP\newrelic-infra.msi")
          }
          catch {
            $baseException = $_.Exception.GetBaseException()
            Write-Host -ForegroundColor Red "Failed to download New Relic Infrastructure Agent ($($baseException.Message))"
            $errorCode = 24 # unknown download error

            switch ($baseException) {
              { $_ -is [Net.WebException] }            { $errorCode = 25 } # web download error
              { $_ -is [IO.IOException] }              { $errorCode = 26 } # file io error
              { $_ -is [UnauthorizedAccessException] } { $errorCode = 26 } # file io error
            }
            exit $errorCode
          }
          '

    install_infra:
      cmds:
        - |
          powershell -command '
          $LICENSE_KEY = "{{.NEW_RELIC_LICENSE_KEY}}"
          $InfraConfig = "C:\\Program Files\\New Relic\\newrelic-infra\\newrelic-infra.yml"

          if (Test-Path $InfraConfig) {
            msiexec.exe /qn /i "$env:TEMP\newrelic-infra.msi" | Out-Null

            (Get-Content $InfraConfig) | Where-Object {
              $_ -notmatch "^staging"
            } | Set-Content $InfraConfig

            (Get-Content $InfraConfig) | Where-Object {
              $_ -notmatch "^enable_process_metrics"
            } | Set-Content $InfraConfig

            (Get-Content $InfraConfig) | Where-Object {
              $_ -notmatch "^status_server_enabled"
            } | Set-Content $InfraConfig

            (Get-Content $InfraConfig) | Where-Object {
              $_ -notmatch "^status_server_port"
            } | Set-Content $InfraConfig

            (Get-Content $InfraConfig) | Foreach-Object {
              $_ -replace "^license_key: .*", ("license_key: " + $LICENSE_KEY) `
            } | Set-Content $InfraConfig

            (Get-Content -raw $InfraConfig) -replace "(?m)^custom_attributes:(?s:.*?)(^\s.+:.+\n)+", "" | Set-Content $InfraConfig

          } else {
            msiexec.exe /qn /i "$env:TEMP\newrelic-infra.msi" GENERATE_CONFIG=true LICENSE_KEY="$LICENSE_KEY" | Out-Null
          }

          $NEW_RELIC_REGION = "{{.NEW_RELIC_REGION}}"
          if ($NEW_RELIC_REGION -ilike "staging") {
            Add-Content -Path $InfraConfig -Value "staging: true" -Force
          }
          Add-Content -Path $InfraConfig -Value "enable_process_metrics: true" -Force
          Add-Content -Path $InfraConfig -Value "status_server_enabled: true" -Force
          Add-Content -Path $InfraConfig -Value "status_server_port: 18003" -Force
          if (Test-Path env:HTTPS_PROXY) {
            (Get-Content $InfraConfig) | Where-Object {
              $_ -notmatch "^proxy"
            } | Set-Content $InfraConfig

            Add-Content -Path $InfraConfig -Value "proxy: $env:HTTPS_PROXY" -Force
          }
          Add-Content -Path $InfraConfig -Value "{{.NRIA_CUSTOM_ATTRIBUTES}}" -Force
          '

    start_infra:
      cmds:
        - powershell -command 'net start newrelic-infra'
        - echo "New Relic infrastructure agent for Windows installed and started"

    assert_agent_status_ok:
      cmds:
        - |
          powershell -command '
            Function isInfraRunning { 
              (Get-Service newrelic-infra -ErrorAction SilentlyContinue | Select-Object Status).Status -eq "Running" 
            }
            $maxRetries = 150
            $tries = 0
            while ($tries -lt $maxRetries) {
              $tries += 1
              $statusCheckOutput = ""
              try {
                $statusCheckOutput=Invoke-WebRequest -UseBasicParsing -Method Get -Uri http://localhost:18003/v1/status/errors | Select-Object -ExpandProperty Content;
              } catch { }
              if ($statusCheckOutput -ieq "{}") {
                Write-Host "Agent status check ok."
                break
              }
              if ($statusCheckOutput -ieq "") {
                if ($tries -eq $maxRetries) {
                  if (isInfraRunning) {
                    Write-Host "detected newrelic-infra service running"
                    exit 0
                  }
                  Write-Host -ForegroundColor Red "infra-agent status endpoint not available";
                  exit 32;
                }
              } else {
                if ($tries -eq $maxRetries) {
                  if (isInfraRunning) {
                    Write-Host "detected newrelic-infra service running"
                    exit 0
                  }
                  Write-Host -ForegroundColor Red "infra-agent status check not healthy: $statusCheckOutput";
                  exit 33;
                }
              }
              Start-Sleep -s 2
            }
          '

    collect_meta:
      silent: true
      ignore_error: true
      cmds:
        - |
          powershell -command '
          $version = (Get-WmiObject -class Win32_OperatingSystem).Caption
          $metadata = @"
          {
            "Metadata": 
            {
                "version": "$version"
            }
          } 
          "@
          try { 
            $metadata | Set-Content {{.NR_CLI_OUTPUT}} 
          } catch {}
          '

postInstall:
  info: |2
      ⚙️  The Infrastructure Agent configuration file can be found in C:\Program Files\New Relic\newrelic-infra\newrelic-infra.yml
      Edit these files to make changes or configure advanced features for the agent. See the docs for options:
      Infrastructure Agent: https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings

      Note: Process monitoring has been enabled by default - all other config options are left to the user.
