name: postgresql-open-source-integration
displayName: PostgreSQL Open Source Integration
description: New Relic install recipe for default Postgres Open Source on-host integration (via Infra-Agent)
repository: https://github.com/newrelic/nri-postgresql

installTargets:
  - type: host
    os: linux
    platform: "amazon"
    platformVersion: "2"
  - type: host
    os: linux
    platform: "redhat"
  - type: host
    os: linux
    platform: "centos"

# keyword convention for dealing with search terms that could land someone on this instrumentation project
keywords:
  - Infrastructure
  - Integration
  - postgres

# CLI runs process detection; this is used to filter recipes that are appropriate for matched processes
processMatch:
  - postgres

# Matches partial list of the Log forwarding parameters
logMatch:
  - name: postgresql
    file: /var/log/postgresql/postgresql*.log

validationNrql: "SELECT count(*) from PostgresqlDatabaseSample where hostname like '{{.HOSTNAME}}%' FACET entityGuid SINCE 10 minutes ago"

inputVars:
  - name: "NR_CLI_USERNAME"
    prompt: "Postgres Username"
  - name: "NR_CLI_PASSWORD"
    prompt: "Postgres Password"
  - name: "NR_CLI_DATABASE"
    prompt: "Postgres Database (default: postgres)"
    default: "postgres"
  - name: "NR_CLI_PORT"
    prompt: "Postgres Port (default: 5432)"
    default: 5432
  - name: "NR_CLI_SSL"
    prompt: "Use SSL to connect? (true/false)"
  - name: "NR_CLI_CERT_AUTH_FILE"
    prompt: "Certificate Authority file (if applicable)"
  - name: "NR_CLI_TRUST_SERVER_CERTIFICATE"
    prompt: "Trust certificate? (true/false)"
  - name: "NR_CLI_CLIENT_CERT_FILE"
    prompt: "Client Certificate file (if applicable)"
  - name: "NR_CLI_CERT_KEY"
    prompt: "PEM key file (if applicable)"

preInstall:
  info: |2
      To capture data from the RabbitMQ integration, you'll first need to meet these prerequisites:
      - PostgreSQL version requirement (see https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/postgresql-monitoring-integration#comp-req)
      - User with READ permissions
      
      To create a new user, use these commands as reference (Note: username, 
      password, and similar user-specific values must be replaced):
      
      > CREATE USER newrelic WITH PASSWORD 'PASSWORD'
      > GRANT SELECT ON pg_stat_database TO newrelic
      > GRANT SELECT ON pg_stat_database_conflicts TO newrelic
      > GRANT SELECT ON pg_stat_bgwriter TO newrelic

install:
  version: "3"
  silent: true

  tasks:
    default:
      cmds:
        - taks: assert_pre_req
        - task: setup

    assert_pre_req:
      cmds:
        - |
          sudo systemctl is-active --quiet newrelic-infra || (echo "The infrastructure agent is required to install this integration, we recommend going through our guided install path for this pre-requisite which can be found here:  https://docs.newrelic.com/docs/new-relic-guided-installation-overview" >> /dev/stderr; exit 1)

    setup:
      label: "Installing PostgreSQL integration..."
      cmds:
        - |
          sudo mkdir -p "/etc/newrelic-infra/integrations.d"
        - |
          sudo yum update -y
        - |
          sudo yum install nri-postgresql -y
        - |
          if [ -f /etc/newrelic-infra/integrations.d/postgresql-config.yml ]; then
            sudo rm /etc/newrelic-infra/integrations.d/postgresql-config.yml;
          fi
          sudo touch /etc/newrelic-infra/integrations.d/postgresql-config.yml;
        - |
          if [ {{.NR_CLI_SSL}} == false ]; then
            sudo tee -a /etc/newrelic-infra/integrations.d/postgresql-config.yml > /dev/null <<"EOT"
          integration_name: com.newrelic.postgresql
          instances:
            - name: postgres
              command: all_data
              arguments:
                username: {{.NR_CLI_USERNAME}}
                password: {{.NR_CLI_PASSWORD}}
                hostname: localhost
                database: {{.NR_CLI_DATABASE}}
                port: {{.NR_CLI_PORT}}
                collection_list: 'ALL'
                collect_db_lock_metrics: false
                enable_ssl: {{.NR_CLI_SSL}}
                timeout: 10
          EOT
          else
            sudo tee -a /etc/newrelic-infra/integrations.d/postgresql-config.yml > /dev/null <<"EOT"
          integration_name: com.newrelic.postgresql
          instances:
            - name: postgres
              command: all_data
              arguments:
                username: {{.NR_CLI_USERNAME}}
                password: {{.NR_CLI_PASSWORD}}
                hostname: localhost
                database: {{.NR_CLI_DATABASE}}
                port: {{.NR_CLI_PORT}}
                collection_list: 'ALL'
                collect_db_lock_metrics: false
                enable_ssl: {{.NR_CLI_SSL}}
                trust_server_certificate: {{.NR_CLI_TRUST_SERVER_CERTIFICATE}}
                ssl_root_cert_location: {{.NR_CLI_CERT_AUTH_FILE}}
                ssl_cert_location: {{.NR_CLI_CLIENT_CERT_FILE}}
                ssl_key_location: {{.NR_CLI_CERT_KEY}}
                timeout: 10
          EOT
          fi

        - sudo systemctl restart newrelic-infra.service
