name: postgres-open-source-integration
displayName: PostgreSQL Open Source Integration
description: New Relic install recipe for default Postgres Open Source on-host integration (via Infra-Agent)
repository: https://github.com/newrelic/nri-postgresql

dependencies:
  - infrastructure-agent-installer

installTargets:
  - type: host
    os: windows
    kernelArch: x86_64

# keyword convention for dealing with search terms that could land someone on this instrumentation project
keywords:
  - Infrastructure
  - Integration
  - postgres

# CLI runs process detection; this is used to filter recipes that are appropriate for matched processes
processMatch:
  - postgres\.exe

preInstall:
  requireAtDiscovery: |
    powershell -command '
    try{
      if (Get-Service "postgresql*" -ErrorAction SilentlyContinue) {
          exit 132
      }
    }
    catch {}
    exit 1
    '
  info: |2
      To capture data from the PostgreSQL integration, you'll first need to meet these prerequisites:
      - PostgreSQL version requirement (see https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/postgresql-monitoring-integration#comp-req)
      - User with READ permissions

      To create a new user, use these commands as reference (Note: username,
      password, and similar user-specific values must be replaced):

      > CREATE USER newrelic WITH PASSWORD 'PASSWORD';
      > GRANT SELECT ON pg_stat_database TO newrelic;
      > GRANT SELECT ON pg_stat_database_conflicts TO newrelic;
      > GRANT SELECT ON pg_stat_bgwriter TO newrelic;

install:
  version: "3"
  silent: true

  tasks:
    default:
      cmds:
        - task: setup

    setup:
      cmds:
        - |
          exit 131

postInstall:
  info: |2
      ⚙️  The PostgreSQL configuration file can be found in /etc/newrelic-infra/integrations.d/postgresql-config.yml
      Edit this file to make changes or configure advanced features for this integration. See the docs for options:
      https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/postgresql-monitoring-integration#config
