# Visit our schema definition for additional information on this file format
# https://github.com/newrelic/open-install-library/blob/main/docs/recipe-spec/recipe-spec.md#schema-definition

name: memcached-open-source-integration
displayName: Memcached Open Source Integration
description: New Relic install recipe for default Memcached Open Source on-host integration (via Infra-Agent)
repository: https://github.com/newrelic/nri-memcached

dependencies:
  - infrastructure-agent-installer

installTargets:
  - type: host
    os: linux
    platform: "debian"
  - type: host
    os: linux
    platform: "ubuntu"

# keyword convention for dealing with search terms that could land someone on this instrumentation project
keywords:
  - Infrastructure
  - Integration
  - memcached

# Examine Infrastructure events for correlated data
processMatch:
  - memcached
  - memcache

# Matches partial list of the Log forwarding parameters
logMatch:
  - name: memcached
    file: /var/log/memcached.log

# NRQL the newrelic-cli will use to validate the agent/integration this recipe
# installed is successfully sending data to New Relic
validationNrql: "SELECT count(*) from MemcachedSample where hostname like '{{.HOSTNAME}}%' FACET entityGuid SINCE 10 minutes ago"

preInstall:
  info: |2
      To capture data from the Memcached integration, you'll first need to meet these prerequisites:
      - Memcached version requirement (see https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/memcached-monitoring-integration#comp-req)

install:
  version: "3"

  silent: true

  tasks:
    default:
      cmds:
        - task: assert_pre_req
        - task: setup
        - task: restart

    assert_pre_req:
      cmds:
        - |
          IS_INFRA_INSTALLED=$(sudo ps aux | grep newrelic-infra-service | grep -v grep | wc -l)
          if [ $IS_INFRA_INSTALLED -eq 0 ] ; then
            echo "The infrastructure agent is required to install this integration, we recommend going through our guided install path for this pre-requisite which can be found here:  https://docs.newrelic.com/docs/full-stack-observability/observe-everything/get-started/new-relic-guided-install-overview" >&2
            exit 1
          fi

    setup:
      label: "Installing Memcached integration..."
      cmds:
        - sudo apt-get install libmemcached-tools -y > /dev/null
        - |
          sudo mkdir -p "/etc/newrelic-infra/integrations.d"
        - |
          # Get latest definitions and skip any failure because of deprecation
          sudo apt-get -o Acquire::Check-Valid-Until=false update -yq
        - |
          sudo apt-get install nri-memcached -y > /dev/null
        - |
          if [ -f /etc/newrelic-infra/integrations.d/memcached-config.yml ]; then
            sudo rm /etc/newrelic-infra/integrations.d/memcached-config.yml;
          fi
        - |
          
          # try get values from env
          NR_CLI_DB_USERNAME={{.NR_CLI_DB_USERNAME}}
          NR_CLI_DB_PASSWORD={{.NR_CLI_DB_PASSWORD}}
          NR_CLI_HOST={{.NR_CLI_HOST}}
          NR_CLI_PORT={{.NR_CLI_PORT}}

          # Set default values for variables
          NR_CLI_HOST=${NR_CLI_HOST:-localhost}
          NR_CLI_PORT=${NR_CLI_PORT:-11211}
          MAX_RETRIES=3
          TRIES=0 
          CAN_CONNECT=$(curl $NR_CLI_HOST:$NR_CLI_PORT 2>&1 1>/dev/null -s -S | awk -F'[()]' '{print $2}')

          while [[ $TRIES -lt $MAX_RETRIES  && $CAN_CONNECT == "7" ]]; do
            printf "\nPlease enter the port number for your Memcached instance: "
            read -r NR_CLI_PORT
            ((TRIES++))

            CAN_CONNECT=$(curl $NR_CLI_HOST:$NR_CLI_PORT 2>&1 1>/dev/null -s -S | awk -F'[()]' '{print $2}')

            if [ $CAN_CONNECT == "7" ]; then
              printf "\n\nUnable to connect your Memcached instance using provided port.\n" >&2
              if [ ! $TRIES -lt $MAX_RETRIES ]; then exit 7; fi
              echo "Please try again"
            else
              break
            fi
          done
          
          CAN_CONNECT=""
          if [ -z "$NR_CLI_DB_USERNAME" ] && [ -z "$NR_CLI_DB_PASSWORD" ]; then
            CAN_CONNECT=$(memcstat --servers="$NR_CLI_HOST" | grep uptime | wc -l)
          else
            CAN_CONNECT=$(memcstat --servers="$NR_CLI_HOST" --username="$NR_CLI_DB_USERNAME" --password="$NR_CLI_DB_PASSWORD" | grep uptime | wc -l)
          fi

          TRIES=0 
          while [[ $TRIES -lt $MAX_RETRIES && $CAN_CONNECT -eq 0 ]]; do
            printf "\nPlease enter the username for your Memcached instance: "
            read -r NR_CLI_DB_USERNAME
            printf "Please enter the password for your Memcached instance: "
            stty -echo
            read -r NR_CLI_DB_PASSWORD
            stty echo
            ((TRIES++))

            CAN_CONNECT=$(memcstat --servers="$NR_CLI_HOST" --username="$NR_CLI_DB_USERNAME" --password="$NR_CLI_DB_PASSWORD" | grep uptime | wc -l)
            
            if [ $CAN_CONNECT -eq 0 ] ; then
              printf "\n\nUnable to connect your Memcached instance using provided username and password.\n" >&2
              if [ ! $TRIES -lt $MAX_RETRIES ]; then exit 2; else continue; fi
              echo "Please try again"
            fi
          done

          if [ -z $NR_CLI_DB_USERNAME ] && [ -z $NR_CLI_DB_PASSWORD ]; then
            sudo tee /etc/newrelic-infra/integrations.d/memcached-config.yml > /dev/null <<EOT
          integrations:
            - name: nri-memcached
              env:
                # Hostname of the memcached instance.
                # Defaults to localhost.
                HOST: $NR_CLI_HOST
                # Port memcached is running on.
                # Defaults to 11211
                PORT: $NR_CLI_PORT
              inventory_source: config/memcached
              interval: 15
          EOT
          else
            sudo tee /etc/newrelic-infra/integrations.d/memcached-config.yml > /dev/null <<EOT
          integrations:
            - name: nri-memcached
              env:
                # Hostname of the memcached instance.
                # Defaults to localhost.
                HOST: $NR_CLI_HOST
                # Port memcached is running on.
                # Defaults to 11211
                PORT: $NR_CLI_PORT
                # Memcached SASL username. Only required if
                # authentication is enabled.
                USERNAME: $NR_CLI_DB_USERNAME
                # Memcached SASL password. Only required if
                # authentication is enabled.
                PASSWORD: $NR_CLI_DB_PASSWORD
              inventory_source: config/memcached
              interval: 15
          EOT
          fi

    restart:
      cmds:
        - |
          if [ {{.IS_SYSTEMCTL}} -gt 0 ]; then
            sudo systemctl restart newrelic-infra
          else 
            if [ {{.IS_INITCTL}} -gt 0 ]; then
              sudo initctl restart newrelic-infra
            else
              sudo /etc/init.d/newrelic-infra restart
            fi
          fi
      vars:
        IS_SYSTEMCTL:
          sh: command -v systemctl | wc -l
        IS_INITCTL:
          sh: command -v initctl | wc -l

postInstall:
  info: |2
      ⚙️  The Memcached configuration file can be found in /etc/newrelic-infra/integrations.d/memcached-config.yml
      Edit this file to make changes or configure advanced features for this integration. See the docs for options:
      https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/memcached-monitoring-integration#config
