# Visit our schema definition for additional information on this file format
# https://github.com/newrelic/open-install-library/blob/main/docs/recipe-spec/recipe-spec.md#schema-definition

name: mssql-server-integration-installer
displayName: Microsoft/SqlServer Integration
description: New Relic install recipe for the Microsoft SqlServer Integration
repository: https://github.com/newrelic/nri-mssql

dependencies:
  - infrastructure-agent-installer

installTargets:
  - type: host
    os: linux

keywords:
  - Integration
  - SqlServer
  - Windows

processMatch:
  - sqlservr

validationNrql: "SELECT count(*) from MssqlInstanceSample FACET entityGuid SINCE 10 minutes ago WHERE reportingAgent = '{{.INFRA_KEY}}'"

preInstall:
  requireAtDiscovery: |
    exit 132
  info: |
    To capture data from the Microsoft SqlServer integration, we need to create a new SqlServer user with specific permissions (CONNECT, VIEW SERVER STATE, READ).
    The installation will create a strong randomly generated password for that new user.
    Note, this installation requires Sql Server Authentication, also referenced as Mixed mode.
    More information regarding the prerequisites can be found at https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/microsoft-sql-server-monitoring-integration#about

install:
  version: "3"
  silent: true

  tasks:
    default:
      cmds:
        - task: setup

    setup:
      cmds:
        - |
          exit 131
