name: mongodb-open-source-integration
displayName: MongoDB Open Source Integration
description: New Relic install recipe for default MongoDB Open Source on-host integration (via Infra-Agent)
repository: https://github.com/newrelic/nri-mongodb

installTargets:
  - type: host
    os: linux
    platform: "amazon"
    platformVersion: "2"
  - type: host
    os: linux
    platform: "redhat"
  - type: host
    os: linux
    platform: "centos"

keywords:
  - Infrastructure
  - Integration
  - mongodb

processMatch:
  - mongodb
  - mongod

logMatch:
  - name: MongoDB log
    file: /var/log/mongodb/mongod.log

validationNrql: "SELECT count(*) from MongoDatabaseSample where hostname like '{{.HOSTNAME}}%' FACET entityGuid SINCE 10 minutes ago"

inputVars:
  - name: "NR_CLI_USERNAME"
    prompt: "MongoDB Username"
  - name: "NR_CLI_PASSWORD"
    prompt: "MongoDB Password"
  - name: "NR_CLI_CLUSTERNAME"
    prompt: "MongoDB Cluster Name"
    secret: true
  - name: "NR_CLI_AUTH"
    prompt: "MongoDB Auth Source (default: admin)"
    default: "admin"
  - name: "NR_CLI_HOSTNAME"
    prompt: "MongoDB Hostname (default: localhost)"
    default: "localhost"
  - name: "NR_CLI_PORT"
    prompt: "MongoDB Port (default: 27017)"
    default: 27017
  - name: "NR_CLI_SSL"
    prompt: "Use SSL to connect? (false/true)"
    default: false
  - name: "NR_CLI_CLIENT_CERT_FILE"
    prompt: "Client Certificate file (if applicable)"
  - name: "NR_CLI_CERT_AUTH_FILE"
    prompt: "Certificate Authority file (if applicable)"

preInstall:
  info: |2
      To capture data from the MongoDB integration, you'll first need to meet these prerequisites:
      - MongoDB version requirement (see https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/mongodb-monitoring-integration#comp-req)
      - User with clusterMonitor and listCollections roles

      In the MongoDB shell, execute the following commands to create a
      listCollections role and a new user, then assign clusterMonitor and
      listCollections roles to the new user.
      Note: username, password, and similar user-specific values must be replaced.

      In the MongoDB shell run the following command
      > rs.initiate()

      Switch to the admin database
      > use admin

      Use the following command to create the listCollections role:
      > db.createRole({role: "listCollections", privileges: [{ resource: {db:"",collection:""}, actions: ["listCollections"] }], roles: []})

      Use the following commands to create a new user, and assign clusterMonitor and listCollections roles to the user:
      > db.createUser({ user: "username", pwd: "password", roles: [ "clusterMonitor", "listCollections" ]})

install:
  version: "3"
  silent: true

  tasks:
    default:
      cmds:
        - task: assert_pre_req
        - task: setup
        - task: restart

    assert_pre_req:
      cmds:
        - |
          IS_INFRA_INSTALLED=$(sudo ps aux | grep newrelic-infra-service | grep -v grep | wc -l)
          if [ $IS_INFRA_INSTALLED -eq 0 ] ; then
            echo "The infrastructure agent is required to install this integration, we recommend going through our guided install path for this pre-requisite which can be found here:  https://docs.newrelic.com/docs/new-relic-guided-installation-overview" >> /dev/stderr
            exit 1
          fi
        - |
          MONGODB_EXISTS=$(mongo --eval 'db.runCommand({ connectionStatus: 1 })' | grep "ok" | awk '{print $1 $2 $3}')
          if [ $MONGODB_EXISTS != "ok:1"]; then
            echo "Cannot estabilish connection to mongodb, please verify that it's installed correctly."
            exit 2
          fi
        - |
          if [ {{.NR_CLI_SSL}} == true ]; then
            if [ ! -f {{.NR_CLI_CLIENT_CERT_FILE}} ]; then
              echo "[Error]: SSL is true but no client certificate file exist at '{{.NR_CLI_CLIENT_CERT_FILE}}'. See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/mongodb-monitoring-integration#comp-req for more info." >> /dev/stderr
              exit 11
            fi
            if [ ! -f {{.NR_CLI_CERT_AUTH_FILE}} ]; then
              echo "[Error]: Trust certificate is true but no certificate authority file exist at '{{.NR_CLI_CERT_AUTH_FILE}}'. See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/mongodb-monitoring-integration#comp-req for more info." >> /dev/stderr
              exit 13
            fi
          fi

    setup:
      label: "Installing MongoDB integration..."
      cmds:
        - |
          sudo mkdir -p "/etc/newrelic-infra/integrations.d"
        - |
          sudo yum -q makecache -y --disablerepo='*' --enablerepo='newrelic-infra'
        - |
          sudo yum install nri-mongodb -y
        - |
          if [ -f /etc/newrelic-infra/integrations.d/mongodb-config.yml ]; then
            sudo rm /etc/newrelic-infra/integrations.d/mongodb-config.yml;
          fi
        - |
          if [ {{.NR_CLI_SSL}} == true ]; then
            sudo tee /etc/newrelic-infra/integrations.d/mongodb-config.yml > /dev/null <<"EOT"
          integration_name: com.newrelic.mongodb
          instances:
            - name: all
              command: all
              arguments:
                # The mongos to connect to
                host: {{.NR_CLI_DB_HOSTNAME}}
                # The port the mongos is running on
                port: {{.NR_CLI_DB_PORT}}
                # The username of the user created to monitor the cluster.
                # This user should exist on the cluster as a whole as well
                # as on each of the individual mongods.
                username: {{.NR_CLI_DB_USERNAME}}
                # The password for the monitoring user
                password: {{.NR_CLI_DB_PASSWORD}}
                # The database on which the monitoring user is stored
                auth_source: {{.NR_CLI_DB_AUTH}}
                # A user-defined cluster name. Required.
                cluster_name: {{.NR_CLI_DB_CLUSTERNAME}}
                # Connect using SSL
                ssl: true
                # Path to the CA certs file
                ssl_ca_certs: {{.NR_CLI_CERT_AUTH_FILE}}
                # Client Certificate to present to the server (optional)
                pem_key_file: {{.NR_CLI_CLIENT_CERT_FILE}}
          EOT
          else
            sudo tee /etc/newrelic-infra/integrations.d/mongodb-config.yml > /dev/null <<"EOT"
          integration_name: com.newrelic.mongodb
          instances:
            - name: all
              command: all
              arguments:
                # The mongos to connect to
                host: {{.NR_CLI_DB_HOSTNAME}}
                # The port the mongos is running on
                port: {{.NR_CLI_DB_PORT}}
                # The username of the user created to monitor the cluster.
                # This user should exist on the cluster as a whole as well
                # as on each of the individual mongods.
                username: {{.NR_CLI_DB_USERNAME}}
                # The password for the monitoring user
                password: {{.NR_CLI_DB_PASSWORD}}
                # The database on which the monitoring user is stored
                auth_source: {{.NR_CLI_DB_AUTH}}
                # A user-defined cluster name. Required.
                cluster_name: {{.NR_CLI_DB_CLUSTERNAME}}
                # Connect using SSL
                ssl: false
          EOT
          fi

    restart:
      cmds:
        - |
          if [ {{.IS_SYSTEMCTL}} -gt 0 ]; then
            sudo systemctl restart newrelic-infra
          else 
            if [ {{.IS_INITCTL}} -gt 0 ]; then
              sudo initctl restart newrelic-infra
            else
              sudo /etc/init.d/newrelic-infra restart
            fi
          fi
      vars:
        IS_SYSTEMCTL:
          sh: which systemctl | wc -l
        IS_INITCTL:
          sh: which initctl | wc -l

postInstall:
  info: |2
      ⚙️  The MongoDB configuration file can be found in /etc/newrelic-infra/integrations.d/mongodb-config.yml
      Edit this file to make changes or configure advanced features for this integration. See the docs for options:
      https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/mongodb-monitoring-integration#config
