# Visit our schema definition for additional information on this file format
# https://github.com/newrelic/open-install-library/blob/main/docs/recipe-spec/recipe-spec.md#schema-definition

name: kafka-open-source-integration
displayName: kafka Open Source Integration
description: New Relic install recipe for default kafka Open Source on-host integration (via Infra-Agent)
repository: https://github.com/newrelic/nri-kafka

dependencies:
  - infrastructure-agent-installer

installTargets:
  - type: host
    os: windows
    kernelArch: x86_64

keywords:
  - Infrastructure
  - Integration
  - kafka

# Kafka runs under java process in windows, so we checking if kafka port 9092 is running under Java
processMatch:
  - java.*kafka

preInstall:
  requireAtDiscovery: |
    powershell -command '
    exit 132
    '
  info: |2
      To capture data from the kafka integration, you'll first need to meet these prerequisites:
      - kafka version requirement (see https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/kafka-monitoring-integration/#req)

install:
  version: "3"
  silent: true

  tasks:
    default:
      cmds:
        - task: setup

    setup:
      cmds:
        - |
          exit 131

postInstall:
  info: |2
      ⚙️  The kafka configuration file can be found in /etc/newrelic-infra/integrations.d/kafka-config.yml
      Edit this file to make changes or configure advanced features for this integration. See the docs for options:
      https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/kafka-monitoring-integration/#config
