# Visit our schema definition for additional information on this file format
# https://github.com/newrelic/open-install-library/blob/main/docs/recipe-spec/recipe-spec.md#schema-definition

name: nginx-open-source-integration
displayName: NGINX Open Source Integration
description: New Relic install recipe for default NGINX Open Source on-host integration (via Infra-Agent)
repository: https://github.com/newrelic/nri-nginx

installTargets:
  - type: host
    os: linux
    platform: "debian"
  - type: host
    os: linux
    platform: "ubuntu"

keywords:
  - Infrastructure
  - Integration
  - nginx

processMatch:
  - nginx

logMatch:
  - name: nginx
    file: /var/log/nginx/access.log* # assumes log rotation like access.log.0, access.log.1, etc.
    attributes:
      logtype: nginx
  - name: nginx
    file: /var/log/nginx/error.log* # assumes log rotation like error.log.0, error.log.1, etc.
    attributes:
      logtype: nginx-error

validationNrql: "SELECT count(*) from NginxSample where hostname like '{{.HOSTNAME}}' FACET entityGuid SINCE 10 minutes ago"

inputVars:
  - name: "NR_CLI_STUB_STATUS_URL"
    prompt: "NGINX status URL (default: http://127.0.0.1/status)"
    default: "http://127.0.0.1/status"

preInstall:
  info: |2
      To capture data from the NGINX integration, you'll first need to enable
      and configure the applicable extension module:
      - For NGINX Open Source: HTTP stub status module 
      - For NGINX Plus: HTTP status module and HTTP API module

install:
  version: "3"
  silent: true

  tasks:
    default:
      cmds:
        - task: assert_pre_req
        - task: setup

    assert_pre_req:
      cmds:
        - |
          SERVICE_EXIST=$(sudo systemctl status newrelic-infra.service | grep "Active" | wc -l)
          if [ $SERVICE_EXIST -eq 0 ]; then
            echo "The newrelic-infra agent service is not installed on the host, but is required to install this integration." >> /dev/stderr
            exit 1
          fi
        - |
          STUB_STATUS_ENABLED=$(curl {{.NR_CLI_STUB_STATUS_URL}} -s | grep "Active connections:" | wc -l)
          if [ $STUB_STATUS_ENABLED -eq 0 ] ; then
            echo "NGINX HTTP status module must be configured for New Relic to collect data. \n - See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/nginx-monitoring-integration#config for more info." >> /dev/stderr
            exit 2
          fi

    setup:
      label: "Installing NGINX integration..."
      cmds:
        - |
          sudo mkdir -p "/etc/newrelic-infra/integrations.d"
        - |
          sudo apt-get update
        - |
          sudo apt-get install nri-nginx -y
        - |
          if [ -f /etc/newrelic-infra/integrations.d/nginx-config.yml ]; then
            sudo rm /etc/newrelic-infra/integrations.d/nginx-config.yml;
          fi

          sudo touch /etc/newrelic-infra/integrations.d/nginx-config.yml;
        - |
          sudo tee -a /etc/newrelic-infra/integrations.d/nginx-config.yml > /dev/null <<"EOT"
          integration_name: com.newrelic.nginx

          instances:
            - name: nginx-server-metrics
              command: metrics
              arguments:
                # If you're using ngx_http_api_module be certain to use the full path up to and including the version number
                status_url: {{.NR_CLI_STUB_STATUS_URL}}

                # Name of Nginx status module OHI is to query against. discover | ngx_http_stub_status_module | ngx_http_status_module | ngx_http_api_module
                status_module: discover

                # New users should leave this property as `true`, to identify the
                # monitored entities as `remote`. Setting this property to `false` (the
                # default value) is deprecated and will be removed soon, disallowing
                # entities that are identified as `local`.
                # Please check the documentation to get more information about local
                # versus remote entities:
                # https://github.com/newrelic/infra-integrations-sdk/blob/master/docs/entity-definition.md
                remote_monitoring: true
                # validate_certs: true
                # default: true If the status URL is HTTPS with a self-signed certificate, set this to false if you want to avoid certificate validation

            - name: nginx-server-inventory
              command: inventory
              arguments:
                config_path: /etc/nginx/nginx.conf

                # New users should leave this property as `true`, to identify the
                # monitored entities as `remote`. Setting this property to `false` (the
                # default value) is deprecated and will be removed soon, disallowing
                # entities that are identified as `local`.
                # Please check the documentation to get more information about local
                # versus remote entities:
                # https://github.com/newrelic/infra-integrations-sdk/blob/master/docs/entity-definition.md
                remote_monitoring: true #new users should leave remote_monitoring = true

                # status_url is used to identify the monitored entity to which the inventory will be attached.
                status_url: {{.NR_CLI_STUB_STATUS_URL}}
          EOT
        - |
          sudo systemctl restart newrelic-infra.service
