name: nagios-open-source-integration
displayName: Nagios Open Source Integration
description: New Relic install recipe for default Nagios Open Source on-host integration (via Infra-Agent)
repository: https://github.com/newrelic/nri-nagios

installTargets:
  - type: host
    os: linux
    platform: "debian"
  - type: host
    os: linux
    platform: "ubuntu"

# keyword convention for dealing with search terms that could land someone on this instrumentation project
keywords:
  - Infrastructure
  - Integration
  - nagios

# Examine Infrastructure events for correlated data
processMatch:
  - nagios

# Matches partial list of the Log forwarding parameters
# https://docs.newrelic.com/docs/logs/enable-log-management-new-relic/enable-log-monitoring-new-relic/forward-your-logs-using-infrastructure-agent#parameters
logMatch:
  - name: apache
    file: /var/log/apache2/access.log
  - name: apache error
    file: /var/log/apache2/error.log

# NRQL the newrelic-cli will use to validate the agent/integration this recipe
# installed is successfully sending data to New Relic
validationNrql: "SELECT count(*) from NagiosServiceCheckSample where hostname like '{{.HOSTNAME}}' FACET entityGuid SINCE 10 minutes ago"

install:

  version: "3"
  silent: true

  tasks:
    default:
      cmds:
        - task: assert_pre_req
        - task: setup
        - task: restart
        
    assert_pre_req:
      cmds:
        - |
          SERVICE_EXIST=$(sudo systemctl status newrelic-infra.service | grep "Active" | wc -l)
          if [ $SERVICE_EXIST -eq 0 ]; then
            echo "The newrelic-infra agent service is NOT installed on the host, but is required to install this integration." >> /dev/stderr
            exit 1
          fi
        - |
          PLUGINS_EXIST=$(ls /usr/local/nagios/libexec | grep check_users | wc -l)
          if [ $PLUGINS_EXIST -eq 0 ] ; then
            echo "check_users plugin not found in /usr/local/nagios/libexec/ Please make sure that the plugins are installed." >> /dev/stderr
            exit 2
          fi

    setup:
      label: "Installing Nagios integration..."
      cmds:
        - |
          sudo mkdir -p "/etc/newrelic-infra/integrations.d"
        - |
          sudo apt-get update
        - |
          sudo apt-get install nri-nagios -y
        - |
          if [ -f /etc/newrelic-infra/integrations.d/nagios-config.yml ]; then
            sudo rm /etc/newrelic-infra/integrations.d/nagios-config.yml;
          fi

          sudo cp /etc/newrelic-infra/integrations.d/nagios-config.yml.sample /etc/newrelic-infra/integrations.d/nagios-config.yml;

        - | 
          sudo tee /etc/newrelic-infra/integrations.d/service_checks.yml > /dev/null <<"EOT"
          service_checks:
            - name: check_users
              command: ["/usr/local/nagios/libexec/check_users", "-w", "5", "-c", "10"]
              parse_output: true
              labels:
                env: staging
                key1: val1
            - name: check_apt
              command: ["/usr/local/nagios/libexec/check_apt"]
          EOT
        - |
          sudo chown 0600 /etc/newrelic-infra/integrations.d/service_checks.yml
    restart:
      cmds:
        - sudo systemctl restart newrelic-infra.service
