name: nagios-open-source-integration
displayName: nagios Open Source Integration
description: New Relic install recipe for default Nagios Open Source on-host integration (via Infra-Agent)
repository: https://github.com/newrelic/nri-nagios

installTargets:
  - type: host
    os: linux
    platform: amazon
    platformVersion: "2"
  - type: host
    os: linux
    platform: "centos"
  - type: host
    os: linux
    platform: "redhat"

keywords:
  - Infrastructure
  - Integration
  - nagios

processMatch:
  - nagios

logMatch:
  - name: apache
    file: /var/log/httpd/*access_log
  - name: apache error
    file: /var/log/httpd/*error_log

validationNrql: "SELECT count(*) from NagiosServiceCheckSample where hostname like '{{.HOSTNAME}}%' FACET entityGuid SINCE 10 minutes ago"

preInstall:
  info: |2
      To capture data from the Nagios integration, you'll first need to meet these prerequisites:
      - Must have an existing service that conforms to the Nagios Plugin API

install:
  version: "3"
  silent: true

  tasks:
    default:
      cmds:
        - task: assert_pre_req
        - task: setup
        - task: restart

    assert_pre_req:
      cmds:
        - |
          SERVICE_EXIST=$(sudo systemctl status newrelic-infra.service | grep "Active" | wc -l)
          if [ $SERVICE_EXIST -eq 0 ]; then
            echo "The newrelic-infra agent service is NOT installed on the host, but is required to install this integration." >> /dev/stderr
            exit 1
          fi
        - |
          PLUGINS_EXIST=$(ls /usr/local/nagios/libexec | grep check_users | wc -l)
          if [ $PLUGINS_EXIST -eq 0 ] ; then
            echo "check_users plugin not found in /usr/local/nagios/libexec/ - Please make sure that the plugins are installed." >> /dev/stderr
            exit 2
          fi

    setup:
      label: "Installing Nagios integration..."
      cmds:
        - |
          sudo mkdir -p "/etc/newrelic-infra/integrations.d"
        - |
          sudo yum update -y -q
        - |
          sudo yum install nri-nagios -y -q
        - |
          if [ -f /etc/newrelic-infra/integrations.d/nagios-config.yml ]; then
            sudo rm /etc/newrelic-infra/integrations.d/nagios-config.yml;
          fi

          sudo cp /etc/newrelic-infra/integrations.d/nagios-config.yml.sample /etc/newrelic-infra/integrations.d/nagios-config.yml;
          sudo cp /etc/newrelic-infra/integrations.d/nagios-service-checks.yml.sample /etc/newrelic-infra/integrations.d/service-checks.yml;
          sudo chmod 0600 /etc/newrelic-infra/integrations.d/service_checks.yml

    restart:
      cmds:
        - sudo systemctl restart newrelic-infra.service
