name: nagios-open-source-integration
displayName: Nagios Integration
description: New Relic install recipe for default Nagios Open Source on-host integration (via Infra-Agent)
repository: https://github.com/newrelic/nri-nagios

dependencies:
  - infrastructure-agent-installer

installTargets:
  - type: host
    os: linux
    platform: amazon
    platformVersion: "2"
  - type: host
    os: linux
    platform: "centos"
  - type: host
    os: linux
    platform: "redhat"

keywords:
  - Infrastructure
  - Integration
  - nagios

processMatch:
  - nagios

logMatch:
  - name: nagios
    file: /usr/local/nagios/var/nagios.log

validationNrql: "SELECT count(*) from NagiosServiceCheckSample FACET entityGuid SINCE 10 minutes ago WHERE reportingAgent = '{{.INFRA_KEY}}'"

preInstall:
  info: |2
      To capture data from the Nagios integration, you'll first need to meet these prerequisites:
      - Must have an existing service that conforms to the Nagios Plugin API

install:
  version: "3"
  silent: true

  tasks:
    default:
      cmds:
        - task: assert_pre_req
        - task: setup
        - task: restart

    assert_pre_req:
      cmds:
        - |
          IS_INFRA_INSTALLED=$(sudo ps aux | grep newrelic-infra-service | grep -v grep | wc -l)
          if [ $IS_INFRA_INSTALLED -eq 0 ] ; then
            echo "The infrastructure agent is required to install this integration, we recommend going through our guided install path for this pre-requisite which can be found here:  https://docs.newrelic.com/docs/full-stack-observability/observe-everything/get-started/new-relic-guided-install-overview" >&2
            exit 1
          fi
        - |
          PLUGINS_EXIST=$(ls /usr/local/nagios/libexec | grep check_users | wc -l)
          if [ $PLUGINS_EXIST -eq 0 ] ; then
            echo "check_users plugin not found in /usr/local/nagios/libexec/ - Please make sure that the plugins are installed." >&2
            exit 2
          fi

    setup:
      label: "Installing Nagios integration..."
      cmds:
        - |
          sudo mkdir -p "/etc/newrelic-infra/integrations.d"
        - |
          sudo yum -q makecache -y --disablerepo='*' --enablerepo='newrelic-infra'
        - |
          sudo yum install nri-nagios -y
        - |
          if [ -f /etc/newrelic-infra/integrations.d/nagios-config.yml ]; then
            sudo rm /etc/newrelic-infra/integrations.d/nagios-config.yml;
          fi

          sudo cp /etc/newrelic-infra/integrations.d/nagios-config.yml.sample /etc/newrelic-infra/integrations.d/nagios-config.yml;
          sudo chmod 0600 /etc/newrelic-infra/integrations.d/nagios-config.yml

        - |
          sudo tee /etc/newrelic-infra/integrations.d/nagios-service-checks.yml > /dev/null <<"EOT"
          # This file must have permissions 0600 on linux.
          # File permissions are not checked on Windows, so
          # it is the user's responsibility to set permissions
          # appropriately.
          service_checks:
              # name is a user-defined name to identify the service check
            - name: check_users
              # command is a command whose arguments are provided as an array of strings
              command: ["/usr/local/nagios/libexec/check_users", "-w", "5", "-c", "10"]
              parse_output: true
              # labels are an optional block that provide additional user-defined
              # key-value pairs to identify and group the service check
              labels:
                env: staging
                key1: val1
            - name: check_yum
              command: ["/usr/local/nagios/libexec/check_ssh", "localhost"]
              parse_output: true
          EOT
        - |
          sudo chmod 0600 /etc/newrelic-infra/integrations.d/nagios-service-checks.yml

    restart:
      cmds:
        - |
          if [ {{.IS_SYSTEMCTL}} -gt 0 ]; then
            sudo systemctl restart newrelic-infra
          else
            if [ {{.IS_INITCTL}} -gt 0 ]; then
              sudo initctl restart newrelic-infra
            else
              sudo /etc/init.d/newrelic-infra restart
            fi
          fi
      vars:
        IS_SYSTEMCTL:
          sh: command -v systemctl | wc -l
        IS_INITCTL:
          sh: command -v initctl | wc -l

postInstall:
  info: |2
      ⚙️  The Nagios configuration file can be found in /etc/newrelic-infra/integrations.d/nagios-config.yml
      ⚙️  The service checks configuration file can be found in /etc/newrelic-infra/integrations.d/service_checks.yml
      Edit these files to make changes or configure advanced features for this integration. See the docs for options:
      https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/nagios-monitoring-integration#config
