# See http://download.newrelic.com/infrastructure_agent/ for possible permutations of platform/arch
platform: linux

install:

  # go-task yaml definition goes here
  # This spec - https://github.com/go-task/task

  version: '3'

  env:
    NR_LICENSE_KEY: '{{.NR_LICENSE_KEY}}'
    NEW_RELIC_DISTRIBUTED_TRACING_ENABLED: true

  tasks:
      install:
        cmds:
          - task: install_library
          - task: setup_config

      install_library:
        cmds:
          - echo "Installing the newrelic library"
          - npm install --save newrelic
        silent: true

      setup_config:
        cmds:
          - |
            if [ ! -f newrelic.js ]; then
              echo "Enter a name for your application and press [ENTER]:"
              read appname
              echo ""
              echo "Writing the newrelic.js configuration file."
              echo "'use strict'
              /**
               * New Relic agent configuration.
               *
               * See lib/config/default.js in the agent distribution for a more complete
               * description of configuration variables and their potential values.
               */
              exports.config = {
                /**
                 * Array of application names.
                 */
                app_name: ['$appname'],
                /**
                 * Your New Relic license key.
                 */
                license_key: '$NR_LICENSE_KEY',
                /**
                 * This setting controls distributed tracing.
                 * Distributed tracing lets you see the path that a request takes through your
                 * distributed system. Enabling distributed tracing changes the behavior of some
                 * New Relic features, so carefully consult the transition guide before you enable
                 * this feature: https://docs.newrelic.com/docs/transition-guide-distributed-tracing
                 * Default is true.
                 */
                distributed_tracing: {
                  /**
                   * Enables/disables distributed tracing.
                   *
                   * @env NEW_RELIC_DISTRIBUTED_TRACING_ENABLED
                   */
                  enabled: $NEW_RELIC_DISTRIBUTED_TRACING_ENABLED
                },
                logging: {
                  /**
                   * Level at which to log. 'trace' is most useful to New Relic when diagnosing
                   * issues with the agent, 'info' and higher will impose the least overhead on
                   * production applications.
                   */
                  level: 'info'
                },
                /**
                 * When true, all request headers except for those listed in attributes.exclude
                 * will be captured for all traces, unless otherwise specified in a destination's
                 * attributes include/exclude lists.
                 */
                allow_all_headers: true,
                attributes: {
                  /**
                   * Prefix of attributes to exclude from all destinations. Allows * as wildcard
                   * at end.
                   *
                   * NOTE: If excluding headers, they must be in camelCase form to be filtered.
                   *
                   * @env NEW_RELIC_ATTRIBUTES_EXCLUDE
                   */
                  exclude: [
                    'request.headers.cookie',
                    'request.headers.authorization',
                    'request.headers.proxyAuthorization',
                    'request.headers.setCookie*',
                    'request.headers.x*',
                    'response.headers.cookie',
                    'response.headers.authorization',
                    'response.headers.proxyAuthorization',
                    'response.headers.setCookie*',
                    'response.headers.x*'
                  ]
                }
              }
              " >> newrelic.js
            else
              echo "newrelic.js config present. Skipping config file construction."
            fi
          - echo ""
          - echo "Add the following code to the first line of the $appname main module:"
          - echo "require('newrelic');"
        silent: true