name: elasticsearch-open-source-integration
displayName: Elasticsearch Integration
description: New Relic install recipe for default Elasticsearch Open Source on-host integration (via Infra-Agent)
repository: https://github.com/newrelic/nri-elasticsearch

dependencies:
  - infrastructure-agent-installer

installTargets:
  - type: host
    os: linux
    platform: "amazon"
  - type: host
    os: linux
    platform: "redhat"
  - type: host
    os: linux
    platform: "centos"

# keyword convention for dealing with search terms that could land someone on this instrumentation project
keywords:
  - Infrastructure
  - Integration
  - elastic
  - elasticsearch

# CLI runs process detection; this is used to filter recipes that are appropriate for matched processes
processMatch:
  - elasticsearch

# Matches partial list of the Log forwarding parameters
logMatch:
  - name: elasticsearch
    file: /var/log/elasticsearch/elasticsearch*.log

# The newrelic-cli will use this integration name to check the config file(s)
# that were setup during the installation to ensure the integration
# runs properly with the defined environment variables
validationIntegration: elasticsearch

# DEPRECATED
validationNrql: "SELECT count(*) from ElasticsearchClusterSample FACET entityGuid SINCE 10 minutes ago WHERE reportingAgent = '{{.INFRA_KEY}}'"

successLinkConfig:
  type: EXPLORER

inputVars:
  - name: "NR_CLI_API_USERNAME"
    prompt: "ElasticSearch Username"
  - name: "NR_CLI_API_PASSWORD"
    prompt: "ElasticSearch Password"
    secret: true
  - name: "NR_CLI_API_HOSTNAME"
    prompt: "ElasticSearch Hostname (default: localhost)"
    default: "localhost"
  - name: "NR_CLI_API_PORT"
    prompt: "ElasticSearch Port (default: 9200)"
    default: 9200
  - name: "NR_CLI_CONFIG_PATH"
    prompt: "ElasticSearch config file (default: /etc/elasticsearch/elasticsearch.yml)"
    default: "/etc/elasticsearch/elasticsearch.yml"
  - name: "NR_CLI_API_USE_SSL"
    prompt: "Use SSL to connect? (false/true)"
    default: false
  - name: "NR_CLI_API_CA_BUNDLE_DIR"
    prompt: "SSL Certificate Directory (if applicable)"
  - name: "NR_CLI_API_CA_BUNDLE_FILE"
    prompt: "SSL Certificate File (if applicable)"

preInstall:
  info: |2
      To capture data from the Elasticsearch integration, you'll first need to meet these prerequisites:
      - Elasticsearch version requirement (see https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/elasticsearch-monitoring-integration#req)

install:
  version: "3"
  silent: true

  tasks:
    default:
      cmds:
        - task: assert_pre_req
        - task: setup
        - task: restart

    assert_pre_req:
      cmds:
        - |
          IS_INFRA_INSTALLED=$(sudo ps aux | grep newrelic-infra-service | grep -v grep | wc -l)
          if [ $IS_INFRA_INSTALLED -eq 0 ] ; then
            echo "The infrastructure agent is required to install this integration, we recommend going through our guided install path for this pre-requisite which can be found here:  https://docs.newrelic.com/docs/full-stack-observability/observe-everything/get-started/new-relic-guided-install-overview" >&2
            exit 1
          fi
        - |
          if [ ! -f {{.NR_CLI_CONFIG_PATH}} ]; then
            echo "[Error]: The ElasticSearch config file cannot be found at '{{.NR_CLI_CONFIG_PATH}}'. See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/elasticsearch-monitoring-integration#comp-req for more info." >&2
            exit 9
          fi
        - |
          if [ {{.NR_CLI_API_USE_SSL}} == true ]; then
            if [ ! -d {{.NR_CLI_API_CA_BUNDLE_DIR}} ]; then
              echo "[Error]: SSL is true but no certificate bundle directory exist at '{{.NR_CLI_API_CA_BUNDLE_DIR}}'. See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/elasticsearch-monitoring-integration#comp-req for more info." >&2
              exit 11
            fi
            if [ ! -f {{.NR_CLI_API_CA_BUNDLE_DIR}}/{{.NR_CLI_API_CA_BUNDLE_FILE}} ]; then
              echo "[Error]: SSL is true but no client certificate file exist at '{{.NR_CLI_API_CA_BUNDLE_DIR}}/{{.NR_CLI_API_CA_BUNDLE_FILE}}'. See https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/elasticsearch-monitoring-integration#comp-req for more info." >&2
              exit 12
            fi
          fi

    setup:
      label: "Installing Elasticsearch integration..."
      cmds:
        - |
          sudo mkdir -p "/etc/newrelic-infra/integrations.d"
        - |
          sudo yum -q makecache -y --disablerepo='*' --enablerepo='newrelic-infra'
        - |
          sudo yum install nri-elasticsearch -y
        - |
          if [ -f /etc/newrelic-infra/integrations.d/elasticsearch-config.yml ]; then
            sudo rm /etc/newrelic-infra/integrations.d/elasticsearch-config.yml;
          fi

          sudo touch /etc/newrelic-infra/integrations.d/elasticsearch-config.yml;
        - |
          if [ {{.NR_CLI_API_USE_SSL}} == false ]; then
            sudo tee -a /etc/newrelic-infra/integrations.d/elasticsearch-config.yml > /dev/null <<"EOT"
          integrations:
            - name: nri-elasticsearch
              env:
                CLUSTER_ENVIRONMENT: staging
                CONFIG_PATH: {{.NR_CLI_API_CONFIG_PATH}}
                HOSTNAME: {{.NR_CLI_API_HOSTNAME}}
                USERNAME: {{.NR_CLI_API_USERNAME}}
                PASSWORD: {{.NR_CLI_API_PASSWORD}}
                PORT: {{.NR_CLI_API_PORT}}
                TIMEOUT: 30
                USE_SSL: false
                COLLECT_INDICES: true
                COLLECT_PRIMARIES: true
              inventory_source: config/elasticsearch
              interval: 15s
          EOT
          else
            sudo tee -a /etc/newrelic-infra/integrations.d/elasticsearch-config.yml > /dev/null <<"EOT"
          integrations:
            - name: nri-elasticsearch
              env:
                CLUSTER_ENVIRONMENT: staging
                CONFIG_PATH: {{.NR_CLI_API_CONFIG_PATH}}
                HOSTNAME: {{.NR_CLI_API_HOSTNAME}}
                USERNAME: {{.NR_CLI_API_USERNAME}}
                PASSWORD: {{.NR_CLI_API_PASSWORD}}
                PORT: {{.NR_CLI_API_PORT}}
                TIMEOUT: 30
                USE_SSL: true
                CA_BUNDLE_DIR: {{.NR_CLI_API_CA_BUNDLE_DIR}}
                CA_BUNDLE_FILE: {{.NR_CLI_API_CA_BUNDLE_FILE}}
                COLLECT_INDICES: true
                COLLECT_PRIMARIES: true
              inventory_source: config/elasticsearch
              interval: 15s
          EOT
          fi

    restart:
      cmds:
        - |
          if [ {{.IS_SYSTEMCTL}} -gt 0 ]; then
            sudo systemctl restart newrelic-infra
          else 
            if [ {{.IS_INITCTL}} -gt 0 ]; then
              sudo initctl restart newrelic-infra
            else
              sudo /etc/init.d/newrelic-infra restart
            fi
          fi
      vars:
        IS_SYSTEMCTL:
          sh: command -v systemctl | wc -l
        IS_INITCTL:
          sh: command -v initctl | wc -l

postInstall:
  info: |2
      ⚙️  The Elasticsearch configuration file can be found in /etc/newrelic-infra/integrations.d/elasticsearch-config.yml
      Edit this file to make changes or configure advanced features for this integration. See the docs for options:
      https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/elasticsearch-monitoring-integration#config
