name: elasticsearch-open-source-integration
displayName: Elasticsearch Open Source Integration
description: New Relic install recipe for default Elasticsearch Open Source on-host integration (via Infra-Agent)
repository: https://github.com/newrelic/nri-elasticsearch

installTargets:
  - type: host
    os: linux
    platform: "amazon"
    platformVersion: "2"
  - type: host
    os: linux
    platform: "redhat"
  - type: host
    os: linux
    platform: "centos"

# keyword convention for dealing with search terms that could land someone on this instrumentation project
keywords:
  - Infrastructure
  - Integration
  - elastic
  - elasticsearch

# CLI runs process detection; this is used to filter recipes that are appropriate for matched processes
processMatch:
  - elasticsearch

# Matches partial list of the Log forwarding parameters
logMatch:
  - name: elasticsearch
    file: /var/log/elasticsearch/elasticsearch*.log 

validationNrql: "SELECT count(*) from ElasticsearchClusterSample where hostname like '{{.HOSTNAME}}%' FACET entityGuid SINCE 10 minutes ago"

inputVars:
  - name: "NR_CLI_API_USERNAME"
    prompt: "ElasticSearch Username"
  - name: "NR_CLI_API_PASSWORD"
    prompt: "ElasticSearch Password"
  - name: "NR_CLI_API_HOSTNAME"
    prompt: "ElasticSearch Hostname (default: localhost)"
    default: "localhost"
  - name: "NR_CLI_API_PORT"
    prompt: "ElasticSearch Port (default: 9200)"
    default: 9200
  - name: "NR_CLI_CONFIG_PATH"
    prompt: "ElasticSearch config file (default: /etc/elasticsearch/elasticsearch.yml)"
    default: "/etc/elasticsearch/elasticsearch.yml"
  - name: "NR_CLI_API_USE_SSL"
    prompt: "Use SSL to connect? (true/false)"
    default: false
  - name: "NR_CLI_API_CA_BUNDLE_DIR"
    prompt: "SSL certificate Directory (if applicable)"
  - name: "NR_CLI_API_CA_BUNDLE_FILE"
    prompt: "SSL Certificate File (if applicable)"

install:

  version: "3"
  silent: true

  tasks:
    default:
      cmds:
        - task: setup

    setup:
      label: "Installing elasticsearch integration..."
      cmds:
        - |
          sudo mkdir -p "/etc/newrelic-infra/integrations.d"
        - |
          sudo yum update -y
        - |
          sudo yum install nri-elasticsearch -y
        - |
          if [ -f /etc/newrelic-infra/integrations.d/elasticsearch-config.yml ]; then
            sudo rm /etc/newrelic-infra/integrations.d/elasticsearch-config.yml;
          fi

          sudo touch /etc/newrelic-infra/integrations.d/elasticsearch-config.yml;
        - |
          if [ {{.NR_CLI_API_USE_SSL}} == false ]; then
            sudo tee -a /etc/newrelic-infra/integrations.d/elasticsearch-config.yml > /dev/null <<"EOT"
          integration_name: com.newrelic.elasticsearch

          instances:
            - name: elasticsearch
              command: all
              arguments:
                cluster_environment: staging
                config_path: {{.NR_CLI_API_CONFIG_PATH}}
                hostname: {{.NR_CLI_API_HOSTNAME}}
                local_hostname: localhost
                username: {{.NR_CLI_API_USERNAME}}
                password: {{.NR_CLI_API_PASSWORD}}
                port: {{.NR_CLI_API_PORT}}
                timeout: 30
                indices_regex:
                collect_indices: true
                collect_primaries: true
          EOT
          else
            sudo tee -a /etc/newrelic-infra/integrations.d/elasticsearch-config.yml > /dev/null <<"EOT"
          integration_name: com.newrelic.elasticsearch

          instances:
            - name: elasticsearch
              command: all
              arguments:
                cluster_environment: staging
                config_path: {{.NR_CLI_API_CONFIG_PATH}}
                hostname: {{.NR_CLI_API_HOSTNAME}}
                local_hostname: localhost
                username: {{.NR_CLI_API_USERNAME}}
                password: {{.NR_CLI_API_PASSWORD}}
                port: {{.NR_CLI_API_PORT}}
                timeout: 30
                use_ssl: {{.NR_CLI_API_USE_SSL}}
                ca_bundle_dir: {{.NR_CLI_API_CA_BUNDLE_DIR}}
                ca_bundle_file: {{.NR_CLI_API_CA_BUNDLE_FILE}}
                indices_regex:
                collect_indices: true
                collect_primaries: true
          EOT
          fi
         
        - sudo systemctl restart newrelic-infra.service
