name: Limit PRs on local repo only for E2E tests

on:
  pull_request:
    branches:
      - main

jobs:
  limit_main_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure no fork repo
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          SOURCE_NAME=$(echo ${{ github.event.pull_request.head.repo.full_name }})
          REMOTE_NAME=$(echo ${{ github.event.pull_request.base.repo.full_name }})
          if [ $SOURCE_NAME != $REMOTE_NAME ]; then
            echo "PR should be created from a branch on the source repo, not from a fork, so the E2E tests can run. If you need access please reach out to the #help-virtuoso channel."
            exit 1
          fi
