name: varnish-cache-open-source-integration
displayName: Varnish Cache Open Source Integration
description: New Relic install recipe for default Varnish Open Source on-host integration (via Infra-Agent)
repository: https://github.com/newrelic/nri-varnish

dependencies:
  - infrastructure-agent-installer

installTargets:
  - type: host
    os: linux
    platform: "debian"
  - type: host
    os: linux
    platform: "ubuntu"

# keyword convention for dealing with search terms that could land someone on this instrumentation project
keywords:
  - Infrastructure
  - Integration
  - varnish

# CLI runs process detection; this is used to filter recipes that are appropriate for matched processes
processMatch:
  - varnishd

# Matches partial list of the Log forwarding parameters
logMatch:
  - name: Logs
    file: /var/log/varnish/varnishcna.log

validationNrql: "SELECT count(*) from VarnishSample where hostname like '{{.HOSTNAME}}%' FACET entityGuid SINCE 10 minutes ago"

inputVars:
  - name: "NR_CLI_INSTANCE_NAME"
    prompt: "Instance Name (used to identify data in New Relic)"
  - name: "NR_CLI_PARAMS_CONFIG_FILE"
    prompt: "Location of varnish.params (omit to check defaults)"

preInstall:
  info: |2
      To capture data from the Varnish Cache integration, you'll first need to meet these prerequisites:
      - Varnish Cache version requirement (see https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/varnish-cache-monitoring-integration#comp-req)
      - Location of the varnish.params config file must be known.
      
      If the params_config_file input is empty, the following locations will automatically be checked:
      - /etc/default/varnish/varnish.params
      - /etc/sysconfig/varnish/varnish.params

install:
  version: "3"
  silent: true
  tasks:
    default:
      cmds:
        - task: assert_pre_req
        - task: setup
        - task: restart

    assert_pre_req:
      cmds:
        - |
          IS_INFRA_INSTALLED=$(sudo ps aux | grep newrelic-infra-service | grep -v grep | wc -l)
          if [ $IS_INFRA_INSTALLED -eq 0 ] ; then
            echo "The infrastructure agent is required to install this integration, we recommend going through our guided install path for this pre-requisite which can be found here:  https://docs.newrelic.com/docs/new-relic-guided-installation-overview" >> /dev/stderr
            exit 1
          fi

    setup:
      label: "Installing Varnish Cache integration..."
      cmds:
        - |
          sudo mkdir -p "/etc/newrelic-infra/integrations.d"
        - |
          sudo apt-get update -yq
        - |
          sudo apt-get install nri-varnish -y
        - |
          if [ -f /etc/newrelic-infra/integrations.d/varnish-config.yml ]; then
            sudo rm /etc/newrelic-infra/integrations.d/varnish-config.yml;
          fi
        - |
          if [ -z {{.NR_CLI_PARAMS_CONFIG_FILE}} ]; then
            sudo tee -a /etc/newrelic-infra/integrations.d/varnish-config.yml > /dev/null <<"EOT"
          integration_name: com.newrelic.varnish
          instances:
            - name: varnish
              command: all_data
              arguments:
                instance_name: {{.NR_CLI_INSTANCE_NAME}}
          EOT
          else
            sudo tee -a /etc/newrelic-infra/integrations.d/varnish-config.yml > /dev/null <<"EOT"
          integration_name: com.newrelic.varnish
          instances:
            - name: varnish
              command: all_data
              arguments:
                params_config_file: {{.NR_CLI_PARAMS_CONFIG_FILE}}
                instance_name: {{.NR_CLI_INSTANCE_NAME}} 
          EOT
          fi

    restart:
      cmds:
        - |
          if [ {{.IS_SYSTEMCTL}} -gt 0 ]; then
            sudo systemctl restart newrelic-infra
          else 
            if [ {{.IS_INITCTL}} -gt 0 ]; then
              sudo initctl restart newrelic-infra
            else
              sudo /etc/init.d/newrelic-infra restart
            fi
          fi
      vars:
        IS_SYSTEMCTL:
          sh: which systemctl | wc -l
        IS_INITCTL:
          sh: which initctl | wc -l

postInstall:
  info: |2
      ⚙️  The Varnish Cache configuration file can be found in /etc/newrelic-infra/integrations.d/varnish-config.yml
      Edit this file to make changes or configure advanced features for this integration. See the docs for options:
      https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/varnish-cache-monitoring-integration#config
